import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {LiveGame} from './fixtures/legacy-speech-game.mjs';
import {tickAudience,audienceState,withdrawAudience} from '../modules/live-runtime/audience.mjs';
import {relationshipState,relationshipRecords,relationshipContext,refreshRelationships,spotlightSupporter,noteAudienceArrival} from '../modules/live-runtime/relationships.mjs';
import {recordContribution} from '../modules/pixel-war/honors.mjs';
import {updateCampaign,CAPTURE_MS} from '../modules/pixel-war/campaign.mjs';
import {modelRequest} from '../modules/live-runtime/models.mjs';
const quiet=g=>{g.world.units=[];g.world.mode='test_live';g.world.nextSpawn=g.world.nextGiant=g.world.nextPickup=g.world.nextHazard=g.world.nextWildlife=g.world.nextObjective=1e12;};
function summon(g,viewer='owner-test',reward='rally',side='demon'){g.testGift({side,reward,viewer});g.drain();refreshRelationships(g);return g.world.units.find(u=>u.supporter?.name===({'owner-test':'本机试玩','viewer-b':'试玩乙','viewer-c':'试玩丙'})[viewer]&&u.side===side);}
function say(g,text,viewer='owner-test',side='demon'){const a=audienceState(g);if(a.active[side]){g.world.time=a.active[side].until+1;tickAudience(g);}g.world.time=Math.max(g.world.time,a.nextFree[side]);g.testChat({side,text,viewer});tickAudience(g);return g.world.speech.at(-1);}
test('same viewer is recognized from selected conversation; unverified claims never become combat deeds',()=>{const g=new LiveGame();try{quiet(g);say(g,'我刚刚救了你');let line=say(g,'还记得我吗');assert(line.text.includes('我刚刚救了你'));assert(line.text.includes('你说'));const r=relationshipRecords(g,'demon')[0];assert.equal(r.facts.length,0);assert.equal(r.kills,0);assert.equal(r.replies,2);line=say(g,'还记得我吗','viewer-b');assert(line.text.includes('提醒我'));assert(!line.text.includes('救了'));}finally{g.close();}});
test('actual shield deployment is remembered once, preserves free ownership, and cannot claim a queued or replayed gift',()=>{const g=new LiveGame();try{quiet(g);const h=g.world.heroes.demon;h.hp=h.maxHP*.2;g.testGift({side:'demon',reward:'aegis',id:'test:shield'});assert.equal(relationshipRecords(g,'demon')[0].shields,0);g.drain();refreshRelationships(g);const r=relationshipRecords(g,'demon')[0];assert.equal(r.shields,180);g.testGift({side:'demon',reward:'aegis',id:'test:shield'});g.drain();refreshRelationships(g);assert.equal(r.shields,180);assert(say(g,'还记得我吗').text.includes('护盾'));const points=g.meta.points.demon;say(g,'我的战绩');assert.equal(g.meta.points.demon,points);assert.equal(h.shield,180);}finally{g.close();}});
test('real kills, healing and complete troop loss feed remembered facts and proactive remarks without changing battle RNG',()=>{const g=new LiveGame({audienceDriven:false});try{quiet(g);const u=summon(g),other=summon(g,'viewer-b','mercy'),w=g.world,h=w.heroes.demon;for(let i=0;i<5;i++){w.spawn('human','militia',1);const target=w.units.at(-1);w.resolveHit(u,target,1e6);}h.hp=h.maxHP*.2;h.hp+=15;recordContribution(w,other,h,0,15);refreshRelationships(g);const rows=relationshipRecords(g,'demon'),r=rows.find(r=>r.supporter.id===u.supporter.id);assert.equal(r.kills,5);assert(rows.find(r=>r.supporter.id===other.supporter.id).facts.some(f=>f.type==='rescue'));for(const member of w.units.filter(v=>v.side==='demon'&&v.supporter?.id===u.supporter.id&&v.hp>0))w.resolveHit(w.heroes.human,member,1e6);refreshRelationships(g);assert(r.facts.some(f=>f.type==='loss'));const seed=w.seed;w.time+=6001;spotlightSupporter(g);assert(w.speech.at(-1).community);assert(w.speech.at(-1).text.includes('抬上来'));assert.equal(w.seed,seed);const n=w.speech.length;spotlightSupporter(g);assert.equal(w.speech.length,n);}finally{g.close();}});
test('capture gives each present summoner shared participation credit, no sole-credit fiction',()=>{const g=new LiveGame();try{quiet(g);const a=summon(g),b=summon(g,'viewer-b');const site=g.world.campaign.sites.find(p=>p.owner==='human'&&p.kind==='grain');for(const u of g.world.units){u.x=site.x;u.y=site.y;}g.world.heroes.human.x=site.x+2000;g.world.heroes.demon.x=site.x-2000;site.progress=CAPTURE_MS-1;site.claimFor='demon';updateCampaign(g.world,50);refreshRelationships(g);for(const unit of [a,b]){const r=relationshipRecords(g,'demon').find(r=>r.supporter.id===unit.supporter.id);assert.equal(r.captures,1);assert(r.facts.find(f=>f.type==='capture').text.includes('参与'));}}finally{g.close();}});
test('accepted advice records actual distance outcome; another viewer cannot take its credit',()=>{const g=new LiveGame();try{quiet(g);say(g,'首领后退');const s=relationshipState(g,'demon'),r=relationshipRecords(g,'demon')[0],h=g.world.heroes.demon;assert(s.advice);h.x-=150;g.world.time=s.advice.until+1;refreshRelationships(g);assert(r.facts.some(f=>f.type==='advice_result'&&f.text.includes('距离已经拉开')));assert(say(g,'我的战绩').text.includes('后退'));assert(!say(g,'我的战绩','viewer-b').text.includes('采纳'));}finally{g.close();}});
test('identity is platform and side scoped, bounded, transactional and durable; only fallen persona loses relationships',async()=>{const dir=await mkdtemp(join(tmpdir(),'duel-rel-'));let g=new LiveGame({path:join(dir,'save.sqlite')});try{quiet(g);say(g,'记得我的皇冠');say(g,'守住就行','viewer-b','human');const before=relationshipState(g,'demon').persona;g.close();g=new LiveGame({path:join(dir,'save.sqlite')});assert.equal(relationshipState(g,'demon').persona,before);assert(say(g,'还记得我吗').text.includes('皇冠'));const h=relationshipState(g,'human');g.world.heroes.demon.hp=0;tickAudience(g);assert.equal(Object.keys(relationshipState(g,'demon').memory.active).length,0);assert.equal(Object.keys(h.memory.active).length,1);g.world.heroes.demon=g.world.makeHero('demon',1);assert(say(g,'还记得我吗').text.includes('提醒我'));for(let i=0;i<140;i++)noteAudienceArrival(g,{side:'demon',supporter:{id:String(i),platform:i%2?'test':'bilibili',name:'同名'}});assert(Object.keys(relationshipState(g,'demon').memory.active).length<=128);const n=Object.keys(relationshipState(g,'demon').memory.active).length;assert.throws(()=>g.atomic(()=>{noteAudienceArrival(g,{side:'human',supporter:{id:'rollback',platform:'test',name:'不应保存'}});throw Error('rollback');}));assert(!relationshipRecords(g,'human').some(r=>r.supporter.name==='不应保存'));assert.equal(Object.keys(relationshipState(g,'demon').memory.active).length,n);}finally{g.close();await rm(dir,{recursive:true});}});
test('Luna receives bounded factual relationship context and withdrawn chat is removed from future recall',()=>{const g=new LiveGame();try{quiet(g);g.receive({id:'bilibili:sc:1',messageId:'bilibili:message:1',platform:'bilibili',actor:'a',at:Date.now(),kind:'chat',text:'先守桥再聊天',supporter:{name:'桥头的人'},amountMilli:30000});tickAudience(g);g.runtime.modelEnabled=true;g.world.time=g.meta.audience.active.demon.until+1;tickAudience(g);g.receive({id:'bilibili:chat:2',platform:'bilibili',actor:'a',at:Date.now(),kind:'chat',text:'还记得我吗',supporter:{name:'桥头的人'}});tickAudience(g);const c=g.context('demon'),rel=c.audience.relationships;assert.equal(rel.viewer.name,'桥头的人');assert(rel.viewer.previousExchanges.some(e=>e.viewerSaid==='先守桥再聊天'));const request=modelRequest('luna-max',c);assert(request.input[0].content.includes('facts 是引擎验证'));assert(Buffer.byteLength(request.input[1].content)<12000);withdrawAudience(g,['bilibili:message:1']);const state=relationshipState(g,'demon');assert(relationshipRecords(g,'demon').every(r=>r.exchanges.length===0));}finally{g.close();}});
test('gift notice is not stored or read aloud as a made-up viewer utterance',()=>{const g=new LiveGame();try{quiet(g);g.configureMappings([{platform:'bilibili',giftId:123,reward:'rally',multiplier:1}]);g.receive({id:'bilibili:gift:1',platform:'bilibili',actor:'a',at:Date.now(),kind:'gift',giftId:123,quantity:1,paid:true,amountMilli:1000,supporter:{name:'援军玩家'}});tickAudience(g);const line=g.world.speech.at(-1);assert.equal(line.quote.notice,'gift');assert(!line.spokenText.includes('说：'));assert.equal(relationshipRecords(g,'demon')[0].exchanges.length,0);}finally{g.close();}});
test('a mass casualty frame is accounted fully without retaining a growing event log',()=>{const g=new LiveGame();try{quiet(g);const source=summon(g),w=g.world;for(let i=0;i<120;i++){const target={id:'casualty-'+i,side:'human',kind:'militia',hp:0,deadAt:null};recordContribution(w,source,target,10,0);}refreshRelationships(g);const r=relationshipRecords(g,'demon')[0];assert.equal(r.kills,120);assert.equal(w.supporterEvents.items.length,0);refreshRelationships(g);assert.equal(r.kills,120);}finally{g.close();}});
test('withdrawing an accepted paid suggestion removes remembered words and its delayed follow-up',()=>{const g=new LiveGame();try{quiet(g);g.receive({id:'bilibili:sc:delete',messageId:'bilibili:message:delete',platform:'bilibili',actor:'a',at:Date.now(),kind:'chat',text:'首领撤退',supporter:{name:'参谋'},amountMilli:30000});tickAudience(g);assert(relationshipState(g,'demon').advice);withdrawAudience(g,['bilibili:message:delete']);g.world.time+=20000;refreshRelationships(g);const s=relationshipState(g,'demon');assert(!s.advice);assert(relationshipRecords(g,'demon').every(r=>!r.facts.some(f=>f.type.startsWith('advice'))&&r.exchanges.length===0));}finally{g.close();}});
test('ancestor prompt excludes the defeated leaders audience chat history',()=>{const g=new LiveGame();try{quiet(g);say(g,'这顶皇冠像锅盖');const a=audienceState(g);g.world.time=a.active.demon.until+1;tickAudience(g);assert(relationshipRecords(g,'demon')[0].exchanges.some(m=>m.text==='这顶皇冠像锅盖'));assert.equal(g.context('demon').audience.relationships.viewer,null);g.world.heroes.demon=g.world.makeHero('demon',1);assert.equal(g.context('demon').audience.recent.length,0);assert.equal(g.context('demon').audience.relationships.viewer,null);}finally{g.close();}});
test('crowded battlefield retains current evidence within the bridge request limit',async()=>{const {UNIT_KEYS}=await import('../modules/pixel-war/world.mjs');const g=new LiveGame();try{const u=g.world.units[0];g.world.units=['demon','human'].flatMap(side=>UNIT_KEYS.flatMap(kind=>[0,1,2].map(lane=>({...u,side,kind,lane}))));for(let i=0;i<3;i++){noteAudienceArrival(g,{side:'demon',supporter:{id:'p'+i,platform:'test',name:'张'.repeat(24)}});const r=relationshipState(g,'demon').memory.active['test:p'+i].record;r.facts=Array.from({length:4},(_,at)=>({type:'rescue',text:'援军'.repeat(35),at}));r.exchanges=Array.from({length:2},()=>({text:'观众'.repeat(40),reply:'首领'.repeat(40)}));}g.meta.audience.active.demon={phase:'waiting_model',id:'test:selected',text:'还记得我吗',intent:{type:'chat'},supporter:{id:'p0',platform:'test'}};g.meta.personas[g.world.heroes.demon.id]=Array(6).fill('战况'.repeat(70));const c=g.context('demon');assert(Buffer.byteLength(JSON.stringify(c))<=11500);assert(c.audience.relationships.viewer.facts.length>=1);assert.equal(c.units.length,126);assert.doesNotThrow(()=>modelRequest('luna-max',c));}finally{g.close();}});
