import {voiceSegments} from '../modules/live-runtime/speech-turn.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {audienceState,tickAudience,withdrawAudience,voiceCompleted} from '../modules/live-runtime/audience.mjs';
import {relationshipRecords} from '../modules/live-runtime/relationships.mjs';
import {modelRequest,validateDecision} from '../modules/live-runtime/models.mjs';
import {tickMonologues} from '../modules/live-runtime/speech-turn.mjs';
import {selectedLeaderSpeech} from '../modules/pixel-war/public/leader-speech.mjs';
const model='gpt-5.6-luna';
const lines=['我是索恩，眼前那个拿弓的是阿岚。','他往桥那头退了，我得盯着点。','别等我挨了箭才笑啊。'];
function setup(){const g=new LiveGame();g.runtime.modelEnabled=true;g.testChat({side:'demon',text:'你是谁'});tickAudience(g);const c=g.context('demon'),d={strategy:'auto',tactic:'hold',lane:1,speech:lines[0],continuations:lines.slice(1),memory:'',replyTo:c.audience.selected.id,audienceAction:'none'};return {g,c,d};}
test('generated connected reply publishes sequential boxes; memory only contains delivered words',()=>{const {g,c,d}=setup();try{const request=modelRequest('luna-max',c);assert(request.text.format.schema.required.includes('continuations'));assert.equal(JSON.parse(request.input[1].content).interactionRules.enlist,c.interactionRules.enlist);assert(g.applyDecision(c,validateDecision(JSON.stringify(d),c),model));for(let i=0;i<3;i++){const line=selectedLeaderSpeech(g.snapshot(),'demon');assert.equal(line.text,lines[i]);assert.equal(line.segment,i+1);assert.equal(!!line.quote,i===0);assert.equal(relationshipRecords(g,'demon')[0].exchanges.at(-1).reply,lines.slice(0,i+1).join(''));g.world.time=line.until+1;tickAudience(g);}assert.equal(audienceState(g).history.at(-1).reply,lines.join(''));assert.equal(audienceState(g).active.demon,undefined);}finally{g.close();}});
test('a real followup interrupts unspoken continuation and gets current conversation context',()=>{const {g,c,d}=setup();try{assert(g.applyDecision(c,d,model));g.testChat({side:'demon',text:'那你为什么和他打'});g.world.time=audienceState(g).active.demon.until+1;tickAudience(g);const next=g.context('demon');assert.equal(next.audience.selected.text,'那你为什么和他打');assert.equal(next.audience.relationships.viewer.previousExchanges.at(-1).leaderReplied,lines[0]);assert(!JSON.stringify(next).includes(lines[1]));}finally{g.close();}});
test('voice completion owns each box duration; a completed old voice cannot retime the next box',()=>{const {g,c,d}=setup();try{g.runtime.voiceEnabled=true;g.applyDecision(c,d,model);const first=g.world.speech.at(-1);assert(voiceCompleted(g,first,{audioUrl:'/voice/test.wav',durationMs:4200}));g.world.time=first.until+1;tickAudience(g);assert.equal(g.world.speech.at(-1).segment,2);assert.equal(voiceCompleted(g,first,{audioUrl:'/voice/stale.wav'}),false);}finally{g.close();}});
test('all continuation segments are validated, and cannot invent a viewer memory question',()=>{const {g,c,d}=setup();try{for(const cont of [[0],['https://bad.example'],['认得你，你以前救过我。'],Array(4).fill('再说一句')]){assert.throws(()=>validateDecision(JSON.stringify({...d,continuations:cont}),c));assert.equal(g.applyDecision(c,{...d,continuations:cont},model),false);}}finally{g.close();}});
test('persona death cancels a sequence; monologues also yield to actual audience',()=>{const {g,c,d}=setup();try{g.applyDecision(c,d,model);g.world.heroes.demon.hp=0;tickAudience(g);assert(!g.world.speech.some(s=>s.audienceId===c.audience.selected.id));g.resetForLaunch();g.world.paused=false;const m=g.context('demon');assert(g.applyDecision(m,{strategy:'auto',tactic:'hold',lane:1,speech:'他又往桥边走了。',continuations:['我先看看他想干什么。'],memory:''},model));g.world.audienceWaiting={demon:true};tickMonologues(g.world);assert(!g.world.leaderTurns.demon);}finally{g.close();}});
test('bare enlistment typo summons only free troops; exhibition prose remains chat',()=>{const g=new LiveGame();try{assert.equal(g.testChat({side:'demon',text:'参展'}).status,'recruited');g.drain();g.drain();assert.equal(g.world.units.length,1);assert.equal(g.testChat({side:'demon',text:'参战'}).status,'recruited');g.drain();assert.equal(g.testChat({side:'demon',text:'我想参展我的画'}).status,'message_queued');assert.equal(g.world.units.length,2);}finally{g.close();}});
test('launch reset preserves receipt dedupe/config, replaces both identities and clears all old progression',()=>{const g=new LiveGame();try{const old=g.world,epoch=g.meta.epoch,id=g.world.heroes.demon.id;g.meta.mappings={'bilibili:1':{reward:'rally',multiplier:1}};g.world.ranks={demon:123,human:120};g.world.wins={demon:120,human:123};g.testGift({side:'demon',reward:'rally',id:'test:old-receipt'});g.drain();g.meta.relationships={};g.resetForLaunch();assert.equal(g.world,old);assert(g.meta.epoch>epoch);assert.notEqual(g.world.heroes.demon.id,id);assert.deepEqual(g.world.ranks,{demon:0,human:0});assert.deepEqual(g.world.wins,{demon:0,human:0});assert.equal(g.world.units.length,0);assert.equal(g.world.campaign.front,0);assert.equal(g.world.time,0);assert.equal(g.world.paused,true);assert.equal(g.world.mode,'sparring');assert.equal(g.world.result,null);assert.equal(g.meta.queue.length,0);assert(g.meta.mappings['bilibili:1']);assert.equal(g.runtime.modelEnabled,false);assert(g.testGift({side:'demon',reward:'rally',id:'test:old-receipt'}).duplicate);assert.equal(g.world.units.length,0);g.world.terrainChanges={123:{at:1,kind:1}};assert.equal(g.world.nav.readChanges(),g.world.terrainChanges);const frozenHP=g.world.heroes.demon.hp;for(let i=0;i<200;i++)g.step(50);assert.equal(g.world.time,0);assert.equal(g.world.heroes.demon.hp,frozenHP);assert.equal(g.world.heroes.demon.rank,0);}finally{g.close();}});

test('preloaded leader continues the same generated thought and yields before an actual reply',async()=>{
 const {applySpeechPack,tickLunaSpeech,speechState}=await import('../modules/pixel-war/luna-speech.mjs');const {validateSpeechPack}=await import('../modules/live-runtime/speech-request.mjs');const g=new LiveGame();try{const w=g.world,s=speechState(w);s.pending=[];s.seen={};const r={id:'fixture-scene-chain',side:'demon',persona:w.heroes.demon.id,items:[{cue:'opening'}]},pack={requestId:r.id,lines:[{cue:'opening',text:'你站那么远做什么？',continuations:['弓都举起来了，倒是过来啊。','行，我先挪两步。']}]};validateSpeechPack(JSON.stringify(pack),{speechRequest:r});assert(applySpeechPack(w,r,{ok:true,model,decision:pack},1));s.pending.push({side:'demon',persona:w.heroes.demon.id,cue:'opening',until:30000});tickLunaSpeech(w);assert.equal(w.speech.at(-1).segment,1);w.time=w.speech.at(-1).until+301;tickLunaSpeech(w);assert.equal(w.speech.at(-1).segment,2);assert.equal(w.speech.at(-1).generationId,r.id);w.audienceWaiting={demon:true};tickLunaSpeech(w);assert.equal(s.continuation,null);assert(!w.speech.some(v=>v.segment===3));}finally{g.close();}
});
test('preload does not accept a continuation with links, excessive length, or soldier monologues',async()=>{const {validateSpeechPack}=await import('../modules/live-runtime/speech-request.mjs');for(const [cue,continuations]of [['opening',['https://bad.example']],['opening',['a'.repeat(49)]],['troop_attack',['接着说']]]){const r={id:'fixture-pack',items:[{cue}]};assert.throws(()=>validateSpeechPack(JSON.stringify({requestId:r.id,lines:[{cue,text:'开打了',continuations}]}),{speechRequest:r}));}});

test('long Chinese replies preserve exact words with bounded TTS segments including the trailing fragment',()=>{const parts=['先让你的部队贴着我军侧翼，别单独冲到第1015辈长者面前。','我会压住正面替你们挡反扑，见势不对就收线——活着比逞强重要。'];const chunks=voiceSegments(parts);assert.equal(chunks.join(''),parts.join(''));assert(chunks.every(x=>x.length<=24));assert(chunks.length>2);});
