import test from 'node:test';import assert from 'node:assert/strict';
import {PixelWorld as World} from '../modules/pixel-war/world.mjs';
import {duelManeuver} from '../modules/pixel-war/duel-maneuver.mjs';
import {commanderPlan} from '../modules/pixel-war/strategy.mjs';
const world=()=>new World(37,{audienceDriven:true});
test('pursuit roles are shared, alternate, and terminate; planner never mutates combat or position',()=>{const w=world(),a=w.heroes.demon,b=w.heroes.human,before=[a.x,a.y,a.hp,a.speed];duelManeuver(w,a);w.time=8100;const first=duelManeuver(w,a),second=duelManeuver(w,b);assert.equal(first.order,'retreat');assert.equal(second.order,'chase');assert.deepEqual([a.x,a.y,a.hp,a.speed],before);w.time+=6100;assert.equal(duelManeuver(w,a).order,'duel');w.time+=8600;assert.equal(duelManeuver(w,b).order,'retreat');assert.equal(duelManeuver(w,a).order,'chase');});
test('nearby useful supplies change the withdrawal destination',()=>{const w=world(),a=w.heroes.demon;a.hp=a.maxHP*.5;w.pickups=[{id:'test-heal',kind:'heal',x:a.x-180,y:a.y,until:30000}];duelManeuver(w,a);w.time=8100;duelManeuver(w,a);assert.equal(w.duelManeuver.reason,'supply');assert(Math.abs(w.duelManeuver.goal.x-w.pickups[0].x)<50);});
test('field or leader replacement invalidates a pursuit and explicit orders retain precedence',()=>{const w=world(),a=w.heroes.demon;duelManeuver(w,a);w.time=8100;duelManeuver(w,a);w.fieldEpoch++;duelManeuver(w,a);assert.equal(w.duelManeuver.phase,'engage');w.campaign.orders.demon={kind:'defend',until:50000};assert.equal(commanderPlan(w,a,[w.heroes.human],[]).order,'campaign');});
test('real unattended simulation leaves the bridge, keeps fighting and reengages without changing speed',()=>{const w=world(),samples=[],start={x:w.heroes.demon.x,y:w.heroes.demon.y},speed=w.heroes.demon.speed;for(let i=0;i<2400;i++){w.step(50);if(i%20===0)samples.push({x:w.heroes.demon.x,y:w.heroes.demon.y,gap:Math.hypot(w.heroes.demon.x-w.heroes.human.x,w.heroes.demon.y-w.heroes.human.y),phase:w.duelManeuver?.phase});}assert(samples.some(s=>Math.hypot(s.x-start.x,s.y-start.y)>180));assert(samples.some(s=>s.phase==='maneuver'));assert(w.damageTotals.demon>0&&w.damageTotals.human>0);assert(samples.slice(-30).some(s=>s.gap<260));assert.equal(w.heroes.demon.speed,speed);});
