import test from 'node:test';
import assert from 'node:assert/strict';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {PixelWorld} from '../modules/pixel-war/world.mjs';
import {UNITS,POP_CAP} from '../modules/pixel-war/public/catalog.mjs';
import {battleHonors,recordContribution} from '../modules/pixel-war/honors.mjs';
import {beginSettlement} from '../modules/pixel-war/settlement.mjs';
import {CINEMATIC,LEGACY_CINEMATIC,battleScene,awardRevealCount} from '../modules/pixel-war/public/cinematic.mjs';
import {legacyPackage} from '../modules/pixel-war/public/legacy-catalog.mjs';
import {applyLegacy,deployRetinues,updateLegacies} from '../modules/pixel-war/legacy.mjs';
import {awardKill} from '../modules/pixel-war/progression.mjs';
import {reviveIdentity,rememberFallen,commandOwnedTroops} from '../modules/pixel-war/viewer-troops.mjs';
import {encodeFrame,decodeFrame} from '../modules/pixel-war/public/wire.mjs';
import {playMenu} from '../modules/live-runtime/play-menu.mjs';
const advance=(w,ms)=>{for(let t=0;t<ms;t+=50)w.step(Math.min(50,ms-t));};
function battle(){const w=new PixelWorld();w.units=[];w.mode='test_live';w.nextSpawn=w.nextPickup=w.nextHazard=w.nextWildlife=w.nextGiant=w.nextSurprise=w.nextObjective=1e12;return w;}
function unit(w,side,kind,x=9900,y=1152){const u=w.fighter(side,kind,UNITS[kind],x,y);w.units.push(u);return u;}
test('fifty-place ranking keeps both factions, deterministic ties, no fake viewers, and a stable snapshot',()=>{const w=battle();for(let i=0;i<61;i++){const side=i%2?'demon':'human',a=unit(w,side,'militia');a.source='test';a.supporter={id:'v'+i,name:'模拟'+i,platform:'test'};recordContribution(w,a,{side:side==='demon'?'human':'demon',kind:'militia',hp:100},100+i,0);}const h=battleHonors(w,'human',[w.heroes.demon]);assert.equal(h.board.length,50);assert.equal(h.totalParticipants,61);assert.equal(h.board[0].name,'模拟60');assert(h.board.some(e=>e.side==='demon'));assert(h.board.every((e,i)=>e.rank===i+1&&e.source==='test'));const before=structuredClone(h);Object.values(w.honors.entries)[0].damage+=999999;assert.deepEqual(h,before);assert.equal(awardRevealCount(1599,50),2);assert.equal(awardRevealCount(2300,50),4);assert.equal(awardRevealCount(4900,50),50);assert.equal(battleHonors(battle(),'demon',[]).board.length,0);});
test('conditional ceremony freezes combat, introduces a real retinue once, and keeps old saves on their old schedule',()=>{const g=new LiveGame({audienceDriven:false});try{const w=g.world;w.mode='test_live';w.units=[];const winner=w.heroes.human;winner.hp=1234;w.heroes.demon.hp=0;beginSettlement(w,['demon']);advance(g,w.result.timing.handoff);assert.equal(w.result.retinues.length,1);const ids=w.legacyReserve.demon.map(u=>u.id),hp=winner.hp;assert.equal(ids.length,2);assert.equal(w.units.length,0);g.restore(g.capture());advance(g,w.result.timing.end-w.result.timing.handoff);assert.equal(w.mode,'test_live');assert.equal(winner.hp,hp);assert.deepEqual(w.legacyReserve.demon.map(u=>u.id),ids);advance(g,50);assert(ids.every(id=>w.units.some(u=>u.id===id)));g.restore(g.capture());advance(g,50);assert(ids.every(id=>w.units.filter(u=>u.id===id).length===1));const saved=g.capture();delete saved.world.result.timing;delete saved.world.result.ceremonyVersion;saved.world.mode='settlement';saved.world.result.startedAt=saved.world.time-LEGACY_CINEMATIC.end+50;g.restore(saved);advance(g,50);assert.equal(w.mode,'test_live');assert.equal(w.heroes.human.hp,hp);}finally{g.close();}});
test('new content rotates mechanics at high generations, preserves ownership and locks the receipt to its original package',()=>{const g=new LiveGame();try{assert.throws(()=>g.testGift({side:'demon',reward:'retinue'}),/locked/);g.world.ranks.demon=68;g.world.heroes.demon.rank=68;const first=legacyPackage('demon',68),next=legacyPackage('demon',69);assert.notEqual(first.key,next.key);g.world.paused=true;g.testGift({side:'demon',reward:'retinue',id:'test:legacy'});const receipt=structuredClone(g.meta.queue[0]);assert.equal(receipt.legacy.id,first.id);g.world.ranks.demon=69;g.world.paused=false;g.world.units=[];advance(g,1000);const troops=g.world.units.filter(u=>u.receipt==='test:legacy');assert.equal(troops.length,first.count);assert(troops.every(u=>u.legacy.id===first.id&&u.supporter.id&&u.source==='test'));assert.equal(commandOwnedTroops(g.world,'demon',troops[0].supporter.id,'guard').count,first.count);assert(g.testGift({side:'demon',reward:'retinue',id:'test:legacy'}).duplicate);assert.equal(g.meta.queue.length,0);assert.equal(playMenu(g,'demon').legacy.id,next.id);const restored=decodeFrame(encodeFrame(g.snapshot())).units.find(u=>u.id===troops[0].id);assert.deepEqual(restored.legacy,troops[0].legacy);assert.equal(restored.name,first.name);}finally{g.close();}});
test('each authored combat mechanic has a real consequence, distinct from the cosmetic tutorial',()=>{
 {const w=battle(),u=unit(w,'demon','ranger'),t=unit(w,'human','shield',9960);applyLegacy(w,u,legacyPackage('demon',2));w.resolveHit(u,t,100);assert(t.slowUntil>w.time);}
 {const w=battle(),u=unit(w,'demon','grenadier'),t=unit(w,'human','shield',9960);applyLegacy(w,u,legacyPackage('demon',1));w.resolveHit(u,t,100);const hp=t.hp;w.time+=950;updateLegacies(w);assert(t.hp<hp);}
 {const w=battle(),u=unit(w,'demon','mage'),t=unit(w,'human','shield',9960),a=unit(w,'human','militia',9980),b=unit(w,'human','militia',10000);applyLegacy(w,u,legacyPackage('demon',3));w.resolveHit(u,t,100);assert(a.hp<a.maxHP&&b.hp<b.maxHP);assert(w.events.some(e=>e.type==='explosion'));}
 {const w=battle(),u=unit(w,'demon','colossus'),t=unit(w,'human','shield',9960);applyLegacy(w,u,legacyPackage('demon',6));w.resolveHit(u,t,100);assert(t.stunnedUntil>w.time);assert(Object.keys(w.terrainChanges).length>0);}
 {const w=battle(),u=unit(w,'demon','healer'),t=unit(w,'demon','shield',9930);t.hp=300;Object.assign(w.heroes.demon,{x:u.x,y:u.y,hp:1000});applyLegacy(w,u,legacyPackage('demon',5));w.time=2000;updateLegacies(w);assert(t.hp>300);assert(w.heroes.demon.hp<=1045);}
 {const w=battle(),u=unit(w,'demon','musketeer');applyLegacy(w,u,legacyPackage('demon',4));updateLegacies(w);assert.equal(w.legacyBuildings.length,1);const b=w.legacyBuildings[0];w.time+=1100;updateLegacies(w);assert(u.shield>0);const e=unit(w,'human','colossus',b.x+25,b.y);const before=b.hp;w.time+=1100;updateLegacies(w);assert(b.hp<before);}
 {const w=battle(),u=unit(w,'demon','dreadnought');applyLegacy(w,u,legacyPackage('demon',7));assert.equal(u.shots,3);assert(u.interval>UNITS.dreadnought.interval);}
 {const w=battle(),u=unit(w,'demon','scout');unit(w,'human','shield',u.x+160,u.y);applyLegacy(w,u,legacyPackage('demon',8));w.time=2000;updateLegacies(w);assert(u.hasteUntil>w.time);}
});
test('full population holds an elder retinue in reserve; restoring does not duplicate it or grant free winner HP',()=>{const w=battle();w.heroes.demon.hp=0;beginSettlement(w,['demon']);advance(w,w.result.timing.end);const pending=w.legacyReserve.demon.map(u=>u.id),crowd=unit(w,'demon','militia');crowd.pop=POP_CAP;deployRetinues(w);assert.deepEqual(w.legacyReserve.demon.map(u=>u.id),pending);crowd.hp=0;deployRetinues(w);assert.equal(w.legacyReserve.demon.length,0);assert.equal(w.units.filter(u=>pending.includes(u.id)).length,pending.length);});
test('LV10 veterans keep their level on kills; respawning a legacy never reapplies its bonuses cumulatively',()=>{const w=battle(),p=legacyPackage('demon',25),u=unit(w,'demon','grenadier');u.supporter={id:'v',platform:'test',name:'模拟'};u.source='test';applyLegacy(w,u,p);const hp=u.maxHP,attack=u.attack;const target=unit(w,'human','militia');target.hp=0;awardKill(w,u,target);assert.equal(u.level,10);u.hp=0;rememberFallen(w,u);const replacement=unit(w,'demon','grenadier');reviveIdentity(w,replacement,{supporter:u.supporter,legacy:p,reviveId:u.id});applyLegacy(w,replacement,p);assert.equal(replacement.level,10);assert.equal(replacement.maxHP,hp);assert.equal(replacement.attack,attack);});

test('a later contributor can win beyond 512 identities; a cross-faction viewer has one rank and unknown sources cannot enter',()=>{const w=battle(),target={side:'human',kind:'militia',hp:100};for(let i=0;i<601;i++)recordContribution(w,{id:'u'+i,side:'demon',kind:'militia',source:'test',supporter:{id:'v'+i,platform:'test',name:'模拟'+i}},target,i===600?9999:1,0);const same={id:'same',side:'human',kind:'militia',source:'test',supporter:{id:'v600',platform:'test',name:'模拟600'}};recordContribution(w,same,{...target,side:'demon'},10,0);recordContribution(w,{...same,supporter:{platform:'bilibili',name:'本机试玩'}},{...target,side:'demon'},999999,0);const h=battleHonors(w,'demon',[]);assert.equal(h.totalParticipants,601);assert.equal(h.board[0].score,10009);assert.equal(h.board.filter(e=>e.name==='模拟600').length,1);assert.deepEqual(h.board[0].sides,{demon:9999,human:10});});
test('two defeated sides commit together, duplicate starts are ignored, and historical snapshots do not share mutable timers',()=>{const w=battle();w.heroes.demon.hp=0;w.heroes.human.hp=0;const old=structuredClone(w.ranks),ids=Object.values(w.heroes).map(h=>h.id);beginSettlement(w,['demon','human']);const began=w.result.startedAt;beginSettlement(w,['demon','human']);assert.equal(w.result.startedAt,began);const make=w.makeHero.bind(w);w.makeHero=(s,r)=>{if(s==='human')throw Error('fixture_make_failure');return make(s,r);};assert.throws(()=>advance(w,w.result.timing.handoff),/fixture_make_failure/);assert.deepEqual(w.ranks,old);assert.deepEqual(Object.values(w.heroes).map(h=>h.id),ids);assert(!w.result.handedOff);w.makeHero=make;advance(w,50);assert(w.result.handedOff);assert.equal(w.result.retinues.length,2);assert.equal(w.legacyReserve.demon.length,2);assert.equal(w.legacyReserve.human.length,2);assert.equal(w.result.honors.finishers.length,2);const separate=battle();separate.heroes.demon.defense={until:12345};separate.heroes.human.hp=0;beginSettlement(separate,['human']);advance(separate,100);assert.equal(separate.result.victor.defense.until,12345);});
test('disk reopen preserves the handoff and pending packages survive the next generation',async()=>{const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');const dir=await mkdtemp(join(tmpdir(),'duel-v20-'));let g=new LiveGame({audienceDriven:false,path:join(dir,'world.sqlite')});try{g.world.mode='test_live';g.world.units=[];g.world.heroes.demon.hp=0;beginSettlement(g.world,['demon']);advance(g,g.world.result.timing.handoff);const ids=g.world.legacyReserve.demon.map(u=>u.id),epoch=g.world.fieldEpoch;g.close();g=new LiveGame({audienceDriven:false,path:join(dir,'world.sqlite')});assert.equal(g.world.fieldEpoch,epoch);advance(g,g.world.result.timing.end-g.world.result.timing.handoff);g.world.heroes.demon.hp=0;beginSettlement(g.world,['demon']);advance(g,g.world.result.timing.handoff);assert(ids.every(id=>g.world.legacyReserve.demon.some(u=>u.id===id)));assert.equal(g.world.legacyReserve.demon.length,5);g.close();g=new LiveGame({audienceDriven:false,path:join(dir,'world.sqlite')});assert.equal(g.world.ranks.demon,2);assert.equal(new Set(g.world.legacyReserve.demon.map(u=>u.id)).size,5);}finally{g.close();await rm(dir,{recursive:true,force:true});}});
test('a mapped production gift waits safely before unlock then summons the original entitled package once',()=>{const g=new LiveGame();try{g.configureMappings([{platform:'bilibili',giftId:98765,reward:'retinue',multiplier:1}]);const e={id:'bilibili:retinue-proof',platform:'bilibili',kind:'gift',giftId:98765,side:'human',quantity:1,actor:'fixture-actor',at:Date.now(),supporter:{name:'来源测试'}};assert(g.receive(e).ok);assert(g.meta.queue[0].awaitingLegacy);g.meta.liveEnabled=true;g.world.units=[];g.drain();assert(g.meta.queue[0].awaitingLegacy);assert.equal(g.meta.points.demon,0);g.world.ranks.demon=1;for(let i=0;i<3;i++)g.drain();const own=g.world.units.filter(u=>u.receipt===e.id);assert.equal(own.length,2);assert(own.every(u=>u.side==='demon'&&u.source==='bilibili'&&u.legacy.key==='ember'));assert(g.receive(e).duplicate);assert.equal(g.db.prepare('SELECT status FROM receipts WHERE id=?').get(e.id).status,'deployed');}finally{g.close();}});

test('projectile source copies share the caster cooldown and platform identities cannot collide',()=>{const w=battle(),u=unit(w,'demon','mage'),t=unit(w,'human','shield',9960),a=unit(w,'human','shield',9980),b=unit(w,'human','shield',10000);applyLegacy(w,u,legacyPackage('demon',3));w.resolveHit({...u},t,100);const hp=a.hp;w.resolveHit({...u},t,100);assert.equal(a.hp,hp);w.time+=2000;w.resolveHit({...u},t,100);assert(a.hp<hp);for(const platform of ['bilibili','xiaohongshu'])recordContribution(w,{id:platform,side:'demon',kind:'militia',source:platform,supporter:{id:'same-native-id',platform,name:platform}},t,20,0);assert.equal(battleHonors(w,'demon',[]).totalParticipants,2);});
test('old completed ceremonies stay completed and migration grants no historical retinue',()=>{const g=new LiveGame();try{g.world.ranks={demon:60,human:61};g.world.heroes.demon.rank=60;g.world.heroes.human.rank=61;g.world.mode='test_live';g.world.result={startedAt:g.world.time-29000,winner:'human',dead:['demon'],handedOff:true};g.restore(g.capture());assert.equal(battleScene(g.snapshot()),null);assert.equal(g.world.legacyReserve?.demon?.length||0,0);assert.equal(g.world.legacyReserve?.human?.length||0,0);assert(playMenu(g,'demon').legacy);}finally{g.close();}});
