import {rescueQuote} from '../modules/live-runtime/rescue.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {PLATFORM_GIFTS,resolveGiftMapping} from '../modules/live-runtime/gift-catalog.mjs';
import {giftEntitlement,GIFT_TIERS} from '../modules/pixel-war/public/gift-tiers.mjs';
import {GIFTS} from '../modules/pixel-war/public/gifts.mjs';
import {UNITS,rawDamage} from '../modules/pixel-war/public/catalog.mjs';
import {beginSettlement,advanceSettlement} from '../modules/pixel-war/settlement.mjs';
import {eligibleFallen,retireTroops} from '../modules/pixel-war/service-life.mjs';
import {refreshProgress} from '../modules/pixel-war/progression.mjs';
import {encodeFrame,decodeFrame} from '../modules/pixel-war/public/wire.mjs';
import {mapSquads,squadMapTags} from '../modules/pixel-war/public/squad-map.mjs';
import {overlaps} from '../modules/pixel-war/public/label-layout.mjs';
import {playMenu} from '../modules/live-runtime/play-menu.mjs';
import {giftLegend} from '../modules/pixel-war/public/gift-legend.mjs';
function empty(g){const w=g.world;w.units=[];w.mode='test_live';w.nextSpawn=1e12;w.nextHazard=1e12;w.deployed={human:[],demon:[]};return w;}
function fundRescueFixture(g){const u=g.world.fallenTroops.find(u=>!u.reservedBy);if(!u)return;const q=rescueQuote(g,u.ownerId,u.side);g.meta.rescue??={version:1,accounts:{}};g.meta.rescue.accounts[u.side+':'+u.ownerId]={creditMilli:q.costMilli,supporter:u.supporter,side:u.side};}
function deploy(g,args){if(args.reward==='revive')fundRescueFixture(g);g.testGift({side:'demon',...args});for(let i=0;i<12;i++){g.world.deployed={human:[],demon:[]};g.drain();}}
function death(w,sides){for(const s of sides)w.heroes[s].hp=0;beginSettlement(w,sides);w.time=w.result.startedAt+w.result.timing.end;advanceSettlement(w,0);}
test('every catalog gift has an original local icon and a game entitlement, including both ends',()=>{assert(PLATFORM_GIFTS.bilibili.length>=909);for(const gift of PLATFORM_GIFTS.bilibili){assert(existsSync('modules/pixel-war/public'+gift.icon),gift.name);assert(GIFTS[giftEntitlement(gift).reward]);}const g=new LiveGame();try{const menu=playMenu(g,'demon');assert.equal(menu.previewGifts.length,0);assert.equal(menu.gifts.length,0);assert.equal(menu.catalogScope,"room_unverified");assert(PLATFORM_GIFTS.bilibili.some(x=>giftEntitlement(x).quality?.tier===0));assert(PLATFORM_GIFTS.bilibili.some(x=>giftEntitlement(x).quality?.tier===7));assert.equal(resolveGiftMapping(g,{platform:'bilibili',giftId:31036,quantity:1,paid:true}).reward,'mercy');assert.equal(resolveGiftMapping(g,{platform:'bilibili',giftId:987654321,quantity:1}),null);}finally{g.close();}});
test('gift tiers have increasing individual survivability and sustained damage; repeated quantities also strengthen them',()=>{let last;for(const t of GIFT_TIERS){const g=new LiveGame();try{const w=empty(g),q=giftEntitlement({price:t.from,coinType:t.tier?'gold':'silver',name:'fixture'},1).quality;assert(w.spawn('demon',GIFTS[t.reward].unit,1,true,{source:'test',supporter:{id:'a',platform:'test'},quality:q}));const u=w.units.at(-1),value={hp:u.maxHP,armor:u.armor,dps:u.attack*(u.shots||1)/u.interval};if(last){assert(value.hp>last.hp);assert(value.armor>=last.armor);assert(value.dps>last.dps);}last=value;const npc=w.fighter('human',u.kind,UNITS[u.kind],u.x,u.y),hit=rawDamage(w.heroes.human,u,true);assert(u.hp/hit>npc.hp/rawDamage(w.heroes.human,npc,true));if(t.tier){const combo=giftEntitlement({price:t.from,coinType:'gold',name:'fixture'},10).quality;assert(combo.hpFloor>q.hpFloor);assert(combo.attackFloor>q.attackFloor);}}finally{g.close();}}});
test('ordinary recruit gifts do not silently replace fallen veterans; resurrection restores all eligible owned types once',()=>{const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'muskets'});deploy(g,{reward:'breaker'});deploy(g,{reward:'scouts',viewer:'viewer-b'});const own=w.units.filter(u=>u.supporter.id===w.units[0].supporter.id),other=w.units.find(u=>u.supporter.name==='试玩乙'),ids=own.map(u=>u.id);own[0].level=4;own[0].kills=20;refreshProgress(own[0]);const service=structuredClone(own[0].service),quality=structuredClone(own[0].giftQuality);for(const u of [...own,other])w.resolveHit(w.heroes.human,u,1e9);deploy(g,{reward:'muskets'});assert(!w.units.some(u=>ids.includes(u.id)&&u.hp>0));fundRescueFixture(g);const received=g.testGift({side:'demon',reward:'revive',id:'test:revive-all'});assert.equal(received.status,'queued');assert.equal(g.testGift({side:'demon',reward:'revive',id:'test:second-revive'}).status,'no_fallen_troops');for(let i=0;i<12;i++){w.deployed.demon=[];g.drain();}for(const id of ids){const u=w.units.find(u=>u.id===id);assert(u?.hp>0);assert.equal(u.life,2);}const veteran=w.units.find(u=>u.id===ids[0]);assert.equal(veteran.level,4);assert.equal(veteran.kills,20);assert.deepEqual(veteran.service,service);assert.deepEqual(veteran.giftQuality,quality);assert(w.fallenTroops.some(u=>u.id===other.id));assert(g.testGift({side:'demon',reward:'revive',id:'test:revive-all'}).duplicate);}finally{g.close();}});
test('resurrection respects the exact 60 second boundary, other owners, side and battle-time deadline',()=>{const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'breaker'});const u=w.units[0];w.resolveHit(w.heroes.human,u,1e9);w.time+=60000;assert.equal(eligibleFallen(w,u.supporter.id,'demon').length,1);assert.equal(eligibleFallen(w,u.supporter.id,'human').length,0);w.time++;assert.equal(eligibleFallen(w,u.supporter.id,'demon').length,0);assert.equal(g.testGift({side:'demon',reward:'revive'}).status,'no_fallen_troops');}finally{g.close();}});
test('armies survive all distributions of commander deaths without a retirement event',()=>{for(const seq of [['demon','demon','demon'],['human','human','human'],['demon','human','demon'],['human','demon','human']]){const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'breaker'});const u=w.units[0],id=u.id;for(let i=0;i<3;i++){death(w,[seq[i]]);assert(w.units.some(v=>v.id===id&&v.hp>0));}assert.equal(w.leaderDeaths,3);assert(!w.fallenTroops.some(v=>v.id===id));assert(!w.events.some(e=>e.type==='retire'&&e.target===id));}finally{g.close();}}});
test('simultaneous commander deaths count twice; saved service and wire remain stable; revival retains unlimited service',()=>{const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'fortress'});const u=w.units[0];death(w,['demon','human']);assert.equal(w.leaderDeaths,2);const saved=g.capture();g.restore(saved);const v=g.world.units.find(x=>x.id===u.id);assert.equal(v.service.expiresAtDeath,null);const frame=decodeFrame(encodeFrame(g.snapshot())).units.find(x=>x.id===u.id);assert.equal(frame.remainingBattles,null);assert.deepEqual(frame.giftQuality,v.giftQuality);g.world.resolveHit(g.world.heroes.human,v,1e9);deploy(g,{reward:'revive'});const revived=g.world.units.find(x=>x.id===u.id);assert.equal(revived.life,2);assert.equal(revived.service.expiresAtDeath,null);death(g.world,['human']);assert(g.world.units.some(x=>x.id===u.id));}finally{g.close();}});
test('accepted resurrection waits for population capacity without losing veterans or reviving newly dead units',()=>{const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'rally'});const old=w.units[0];w.resolveHit(w.heroes.human,old,1e9);g.testGift({side:'demon',reward:'revive'});const pop=w.population.bind(w);w.population=()=>160;g.drain();assert(g.meta.queue.some(q=>q.key==='revive'&&q.remaining===1));w.time+=65000;retireTroops(w);assert(w.fallenTroops.some(v=>v.id===old.id));delete w.population;w.deployed.demon=[];g.drain();assert(w.units.some(v=>v.id===old.id&&v.life===2));}finally{g.close();}});
test('every viewer formation has a map name box without overlap; system troops do not create name boxes',()=>{const units=Array.from({length:50},(_,i)=>({id:'u'+i,kind:'militia',side:'demon',hp:100,x:i*73,y:i%6*150,source:'test',supporter:{id:'owner'+i,name:'玩家'+i,platform:'test'}}));units.push({id:'npc',kind:'militia',side:'demon',hp:100,x:0,y:0,source:'system',supporter:{platform:'system'}});const groups=mapSquads(units,'demon'),box={x:500,y:350,w:210,h:130},tags=squadMapTags(groups,box,g=>({x:500+g.x/20,y:350+g.y/8}));assert.equal(tags.length,50);assert.equal(new Set(tags.map(t=>t.group.owner.id)).size,50);for(let i=0;i<tags.length;i++){const t=tags[i];assert(t.x>=box.x&&t.y>=box.y&&t.x+t.w<=box.x+box.w+.01&&t.y+t.h<=box.y+box.h+.01);for(let j=i+1;j<tags.length;j++)assert(!overlaps(t,tags[j]));}});

test('Xiaohongshu observed gifts preserve long IDs and real icons, with car and resurrection playable locally',()=>{assert(PLATFORM_GIFTS.xiaohongshu.length>=104);for(const gift of PLATFORM_GIFTS.xiaohongshu){assert.equal(typeof gift.giftId,'string');assert(existsSync('modules/pixel-war/public'+gift.icon),gift.name);assert(GIFTS[giftEntitlement(gift).reward]);}const car=PLATFORM_GIFTS.xiaohongshu.find(x=>x.name==='炫动跑车'),flower=PLATFORM_GIFTS.xiaohongshu.find(x=>x.name==='送你小花');assert.equal(car.price,1999);assert.equal(giftEntitlement(flower).reward,'revive');const g=new LiveGame();try{empty(g);deploy(g,{side:'human',giftId:car.giftId});const u=g.world.units.find(u=>u.side==='human');assert(u?.giftQuality.tier>=5);assert(u.maxHP>20000);assert.equal(playMenu(g,'human').previewGifts.length,0);assert.equal(playMenu(g,'human').gifts.length,0);}finally{g.close();}});
test('free enlist chat deploys one owned soldier per message with no cooldown and supports free commands',()=>{let now=1800000000000;const g=new LiveGame({now:()=>now});try{empty(g);assert.equal(g.testChat({side:'demon',text:'参战'}).status,'recruited');g.drain();g.drain();const own=g.world.units.filter(x=>x.supporter?.id);assert.equal(own.length,1);assert.equal(g.testChat({side:'demon',text:'参战'}).status,'recruited');g.testChat({side:'demon',text:'2'});assert(own.every(u=>u.viewerOrder?.kind==='retreat'),'owner retreat command reaches recruits');now+=60000;assert.equal(g.testChat({side:'demon',text:'参战'}).status,'recruited');}finally{g.close();}});
test('compact gift legend eventually includes every original icon without unbounded stage rows',()=>{const g=new LiveGame();try{for(const side of ['demon','human']){const rows=PLATFORM_GIFTS[side==='demon'?'bilibili':'xiaohongshu'].map(x=>({...x,...giftEntitlement(x),label:giftEntitlement(x).reward})),expected=new Set(rows.map(x=>x.icon).filter(Boolean)),seen=new Set();for(let t=0;t<5000;t++){const page=giftLegend(rows,t*10000);assert(page.length<=5);for(const row of page)for(const gift of row.gifts)seen.add(gift.icon);}for(const icon of expected)assert(seen.has(icon),icon);}}finally{g.close();}});
test('resurrected veterans retain special firing patterns and cannot rebuild consumed legacy buildings',()=>{const g=new LiveGame();try{const w=empty(g);deploy(g,{reward:'cannons'});const u=w.units[0];Object.assign(u,{interval:6.2,shots:3,armorPen:.35,legacyBuilt:true});w.resolveHit(w.heroes.human,u,1e9);deploy(g,{reward:'revive'});const v=w.units.find(x=>x.id===u.id);assert.equal(v.life,2);assert.equal(v.interval,6.2);assert.equal(v.shots,3);assert.equal(v.armorPen,.35);assert.equal(v.legacyBuilt,true);}finally{g.close();}});
