import test from 'node:test';
import assert from 'node:assert/strict';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {giftEntitlement} from '../modules/pixel-war/public/gift-tiers.mjs';
import {GIFTS} from '../modules/pixel-war/public/gifts.mjs';
import {UNITS,rawDamage,ACTIONS} from '../modules/pixel-war/public/catalog.mjs';
import {trainViewerTroop} from '../modules/pixel-war/viewer-training.mjs';
import {refreshProgress} from '../modules/pixel-war/progression.mjs';
import {releaseProjectiles,projectileImpact} from '../modules/pixel-war/ordnance.mjs';
import roster from './fixtures/bili-priced-roster.json' with {type:'json'};
function spawn(g,item){g.world.units=[];const e=giftEntitlement(item),spec=GIFTS[e.reward],start=g.world.units.length;for(let i=0;i<spec.count*e.multiplier;i++){g.world.deployed.demon=[];assert(g.world.spawn('demon',spec.unit,1,true,{source:'test',supporter:{id:'audit',platform:'test'},quality:e.quality}));Object.assign(g.world.units.at(-1),g.world.ground({x:g.world.heroes.demon.x-500-i*130,y:g.world.heroes.demon.y+250}));}return g.world.units.slice(start);}
function measure(w,squad){let durability=0,pressure=0;for(const u of squad){const incoming=[{weight:.5,kind:'militia',x:u.x+10},{weight:.25,kind:'bow',projectile:true,x:u.x+10},{weight:.25,kind:'musketeer',projectile:true,armorPen:.5,x:u.x-10}];u.face=0;const loss=incoming.reduce((s,a)=>s+a.weight*rawDamage({attack:100,y:u.y,...a},u),0);durability+=u.maxHP/loss*100;
 let sum=0;for(const config of [{armor:0},{armor:60},{armor:120},{armor:60,shield:true},{armor:60,shield:true,face:Math.PI},{armor:30,kind:'rider'}])for(const dense of [false,true]){const targets=[0,...(dense?[45,90]:[])].map((x,i)=>({id:'t'+i,side:'human',life:1,hp:1e9,radius:12,x:u.x+20+x,y:u.y,face:0,kind:'militia',...config,equipment:{offhand:config.shield?'shield':null}}));
 // Source comes from the frontal direction for shield fixtures.
 const source={...u,x:targets[0].x+10,y:u.y};const target=targets[0],space={near:()=>targets.filter(v=>v===target||Math.hypot(v.x-target.x,v.y-target.y)<=source.splash)};w.missiles=[];const a={angle:0,critical:false,xpId:'reference'};
 if(ACTIONS[UNITS[u.kind].action].projectile){releaseProjectiles(w,source,target,a,space,ACTIONS[UNITS[u.kind].action].projectile);const pending=[];for(const m of w.missiles)projectileImpact(w,m,target,space,pending);sum+=pending.reduce((s,h)=>s+h[2],0)*(1+.75*u.crit);}
 else sum+=(u.splash?space.near():[target]).reduce((s,v)=>s+rawDamage(source,v)*(v===target?1:.5),0)*(1+.75*u.crit);
 }
 w.attack(u,{id:'dummy',life:1,x:u.x+10,y:u.y});const cycle=(u.readyAt-w.time)/1000;u.action=null;pressure+=sum/12/cycle+(u.kind==='healer'?u.attack/16*60/1.8:0);
}return {durability,pressure};}
test('all twelve real roster items buy monotonically stronger whole squads, with real projectile/cadence resolution',()=>{const g=new LiveGame();try{g.world.units=[];const plans=roster.map(item=>{const squad=spawn(g,item);return {...item,...measure(g.world,squad),kind:squad[0].kind};});assert.equal(plans.length,12);assert.equal(new Set(plans.map(x=>x.kind)).size,12);for(const a of plans)for(const b of plans)if(b.price>a.price){assert(b.durability>a.durability,`${b.name} durability > ${a.name}`);assert(b.pressure>a.pressure,`${b.name} pressure > ${a.name}: ${b.pressure} ${a.pressure}`);}}finally{g.close();}});
test('price boundaries and former count inversions survive actual training without rounded plateaus',()=>{const g=new LiveGame();try{g.world.units=[];for(const [low,high,p] of [['人气票','比心',1000],['你真好看','私人飞机',99999],['粉丝团灯牌','牛哇牛哇',100],['爱的乐章','落日飞车',199999]]){const make=(name,price)=>({...roster.find(r=>r.name===name),price});const a=measure(g.world,spawn(g,make(low,p))),b=measure(g.world,spawn(g,make(high,p+1)));assert(b.pressure>a.pressure,low);assert(b.durability>a.durability,low);}assert.throws(()=>giftEntitlement({...roster[0],price:NaN}));}finally{g.close();}});
test('quantity batches purchase identical per-unit budgets; bonuses remain as requested',()=>{for(const item of roster){const one=giftEntitlement(item,1);for(const q of [2,10,256,323,1000]){const bulk=giftEntitlement(item,q);assert.deepEqual({...bulk.quality,quantity:1},one.quality);assert.equal(bulk.reward,one.reward);assert.equal(bulk.bonus,one.bonus);}}assert.equal(giftEntitlement(roster.find(x=>x.name==='小花花')).bonus,'revive');});
test('retraining preserves wounds and death, never redistributes a dead squad member budget, and keeps XP growth',()=>{const g=new LiveGame();try{g.world.units=[];const squad=spawn(g,roster.find(x=>x.name==='你真好看')),u=squad[0];u.hp=u.maxHP*.37;const woundedHP=u.hp;g.world.heroes.human.rank=8;trainViewerTroop(g.world,u);assert.equal(u.hp,woundedHP);const stats=[u.maxHP,u.attack,u.hp];assert.equal(trainViewerTroop(g.world,u),false);assert.deepEqual([u.maxHP,u.attack,u.hp],stats);squad[1].hp=0;trainViewerTroop(g.world,u);assert.deepEqual([u.maxHP,u.attack,u.hp],stats);u.level=5;refreshProgress(u);assert(u.maxHP>stats[0]&&u.attack>stats[1]);u.hp=0;g.world.heroes.human.rank++;trainViewerTroop(g.world,u);assert.equal(u.hp,0);}finally{g.close();}});
test('actual batched and separate gift dispatches produce the same six units and capacity retains debts',()=>{const make=quantities=>{const g=new LiveGame();g.world.units=[];const gift=roster.find(x=>x.name==='你真好看');for(const quantity of quantities)g.testGift({side:'demon',giftId:gift.giftId,quantity});const normal=g.world.population;g.world.population=()=>160;g.drain();assert(g.meta.queue.reduce((n,q)=>n+q.remaining,0)>=6);g.world.population=normal;for(let i=0;i<20;i++){g.world.deployed.demon=[];g.drain();}return g;};const a=make([2]),b=make([1,1]);try{const stats=g=>g.world.units.filter(u=>u.source==='test').map(u=>[u.kind,u.maxHP,u.attack,u.armor]);assert.equal(stats(a).length,6);assert.deepEqual(stats(a),stats(b));}finally{a.close();b.close();}});
