import {PROCEDURAL_WEAPONS} from '../modules/pixel-war/public/procedural-weapons.mjs';
import {CINEMATIC} from '../modules/pixel-war/public/cinematic.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {PixelWorld} from '../modules/pixel-war/world.mjs';
import {UNITS,ACTIONS,HERO_WEAPONS,rawDamage,POP_CAP} from '../modules/pixel-war/public/catalog.mjs';
import {sampleActor,directionRow} from '../modules/pixel-war/public/actors.mjs';
import {cameraTarget} from '../modules/pixel-war/public/camera.mjs';
import {FieldNavigation} from '../modules/pixel-war/navigation.mjs';
import {CROSSINGS,CAMPS,WIDTH,passable,clearSegment} from '../modules/pixel-war/public/terrain.mjs';
const advance=(w,ms)=>{for(let i=0;i<ms/50;i++)w.step(50);};

test('large map: all three crossings route around blocked water, rocks and trees',()=>{const nav=new FieldNavigation();assert.equal(passable(2048,956),false);for(const y of CROSSINGS){const a={x:1612,y},b={x:2462,y},path=nav.plan(a,b);assert.ok(path?.length);let prev=a;for(const p of path){assert.ok(clearSegment(prev,p));prev=p;}}});
test('three minutes: commanders commit to combat and contest objectives, autonomous sparring never kills either king',()=>{const w=new PixelWorld(),ids=Object.values(w.heroes).map(h=>h.id);let safeBack=0,checks=0,hazards=0,pickups=0;const attacks={demon:new Set(),human:new Set()},minimum={demon:9000,human:9000};const explored={demon:new Set(),human:new Set()};for(let i=0;i<3600;i++){w.step(50);for(const [s,h]of Object.entries(w.heroes)){minimum[s]=Math.min(minimum[s],h.hp);if(h.action)attacks[s].add(h.action.started);}for(const u of w.allAlive())assert.ok(w.walkable(u));if(i%100===0){const f=w.snapshot().fronts;for(const side of ['demon','human']){const sign=side==='demon'?1:-1;if(sign*(f[side].x-w.heroes[side].x)>150)safeBack++;checks++;explored[side].add(Math.floor(w.heroes[side].y/180));}hazards+=w.hazards.length;pickups+=w.pickups.length;}}
 assert.ok(attacks.demon.size>35&&attacks.human.size>35);assert.ok(minimum.demon<9000&&minimum.human<9000);assert.ok(explored.demon.size>=2&&explored.human.size>=2);assert.ok(w.strategyStats.contested>0);assert.ok(w.strategyStats.claims.demon+w.strategyStats.claims.human>0);assert.ok(w.damageTotals.demon>10000&&w.damageTotals.human>10000);assert.deepEqual(Object.values(w.heroes).map(h=>h.id),ids);assert.ok(Object.values(w.heroes).every(h=>h.hp>=h.maxHP*.35));assert.ok(hazards&&pickups);assert.ok(w.population('demon')<=POP_CAP&&w.population('human')<=POP_CAP);
});
test('melee hit and critical numbers are emitted at contact, with a real range miss',()=>{const w=new PixelWorld(),u=w.fighter('demon','militia',UNITS.militia,1200,896),v=w.fighter('human','shield',UNITS.shield,1238,896);u.crit=1;w.attack(u,v,'slash');assert.equal(u.action.critical,true);w.time=u.action.contactAt-1;assert.equal(w.tickActions([u,v]).length,0);assert.equal(v.hp,720);w.time++;const hits=w.tickActions([u,v]);assert.equal(hits.length,1);assert.equal(hits[0][2],rawDamage(u,v,true));const before=v.hp;w.resolveHit(...hits[0]);const e=w.events.at(-1);assert.equal(e.amount,before-v.hp);assert.equal(e.critical,true);assert.equal(sampleActor(u,w.time).frame,3);assert.equal(w.tickActions([u,v]).length,0);u.action=null;w.attack(u,v,'slash');v.x=1420;w.time=u.action.contactAt;assert.equal(w.tickActions([u,v]).length,0);assert.equal(w.events.at(-1).type,'miss');});
test('ranged release does not instantly apply damage, projectiles must travel',()=>{const w=new PixelWorld(),u=w.fighter('demon','bow',UNITS.bow,1200,896),v=w.fighter('human','shield',UNITS.shield,1380,896);w.units=[u,v];w.attack(u,v,'shoot');w.time=u.action.contactAt;assert.equal(w.tickActions([u,v]).length,0);assert.equal(w.missiles.length,1);const hp=v.hp;w.step(50);assert.equal(v.hp,hp);advance(w,600);assert.ok(v.hp<hp);});
test('equipment changes combat style/range and consistent reusable animation clips',()=>{const w=new PixelWorld();for(const [key,p] of Object.entries(HERO_WEAPONS)){assert.equal(w.equip('demon',key),true);const u=w.heroes.demon;assert.equal(u.equipment.weapon,key);assert.equal(u.range,p.range);assert.equal(u.actionType,p.actionType);w.attack(u,w.heroes.human,u.actionType);assert.equal(sampleActor(u,u.action.contactAt).clip,ACTIONS[p.actionType].clip);}assert.equal(w.equip('demon','file:///private'),false);assert.deepEqual([0,Math.PI/2,Math.PI,-Math.PI/2].map(directionRow),[3,2,1,0]);const dying={...w.heroes.demon,deadAt:0};assert.equal(sampleActor(dying,800).clip,'hurt');assert.equal(sampleActor(dying,800).frame,5);});
test('only the defeated king retires; simultaneous defeat changes both identities and elapsed time never resets a living battlefield',()=>{const w=new PixelWorld();w.beginShowcase();const ids={demon:w.heroes.demon.id,human:w.heroes.human.id};w.heroes.demon.hp=0;w.step(50);assert.deepEqual(w.result.dead,['demon']);advance(w,CINEMATIC.end);assert.notEqual(w.heroes.demon.id,ids.demon);assert.equal(w.heroes.human.id,ids.human);assert.equal(w.heroes.demon.rank,1);assert.equal(w.heroes.demon.maxHP,9720);
 w.beginShowcase();w.heroes.demon.hp=0;w.heroes.human.hp=0;w.step(50);assert.equal(w.result.dead.length,2);advance(w,CINEMATIC.end);assert.deepEqual(w.ranks,{demon:2,human:1});w.beginShowcase();const next=Object.values(w.heroes).map(h=>h.id);w.startedAt=w.time-360000;w.step(50);assert.equal(w.result,null);assert.equal(w.mode,'showcase');advance(w,15000);assert.deepEqual(Object.values(w.heroes).map(h=>h.id),next);
});
test('one referee feeds two independently framed outputs, each initially excludes the other king',()=>{const w=new PixelWorld(),s=w.snapshot(),d=cameraTarget(s,'demon'),h=cameraTarget(s,'human');assert.ok(h.x-d.x>700);assert.ok(Math.abs(d.x-s.heroes.demon.x)<480);assert.ok(Math.abs(h.x-s.heroes.human.x)<480);assert.ok(Math.abs(d.x-s.heroes.human.x)>480);assert.ok(Math.abs(h.x-s.heroes.demon.x)>480);});

test('every equipped part has its required native clip; staff includes both shaft and crystal',async()=>{const {readFile}=await import('node:fs/promises');const {parts}=JSON.parse(await readFile(new URL('../modules/pixel-war/public/lpc/manifest.json',import.meta.url),'utf8'));for(const [key,u] of Object.entries(UNITS)){if(u.machine){assert(PROCEDURAL_WEAPONS.has(u.equipment.weapon));continue;}for(const clip of ['walk',ACTIONS[u.action].clip,'hurt'])for(const p of ['body','head','pants','boots',u.equipment.armor,u.equipment.head,'horns',...(!PROCEDURAL_WEAPONS.has(u.equipment.weapon)?[u.equipment.weapon+'Bg',u.equipment.weapon+'Fg']:[]),...(u.equipment.weapon==='staff'?['staffWoodBg','staffWoodFg']:[])]){assert.ok(parts[p]?.[clip],`${key}: ${p} ${clip}`);const bytes=await readFile(new URL('../modules/pixel-war/public'+parts[p][clip].file,import.meta.url));assert.equal(bytes.toString('ascii',1,4),'PNG');}if(u.equipment.offhand)for(const clip of ['walk',ACTIONS[u.action].clip])assert.ok(parts.shield[clip]);}});

test('new troops emerge from the camp door and follow a clear exit before taking their route',()=>{const w=new PixelWorld();w.spawn('demon','militia',0);const u=w.units.at(-1);assert.equal(u.x,CAMPS.demon.x);assert.equal(u.y,CAMPS.demon.y+12);assert.ok(u.exitGoal);advance(w,2200);assert.equal(u.exitGoal,null);assert.ok(u.x>CAMPS.demon.x+130);});

test('screen-edge enemy guide points in eight directions, uses commander distance and hides when visible',async()=>{
 const {enemyIndicator}=await import('../modules/pixel-war/public/indicators.mjs');const camera={x:1536,y:896},own={x:1300,y:850};
 for(const [dx,dy] of [[-1000,0],[1000,0],[0,-700],[0,700],[-1000,-700],[1000,-700],[-1000,700],[1000,700]]){const e={x:camera.x+dx,y:camera.y+dy,hp:4500,maxHP:9000};const m=enemyIndicator(camera,e,own);assert(m);assert(m.x>=28&&m.x<=932&&m.y>=105&&m.y<=415);assert(Math.abs(m.angle-Math.atan2(dy,dx))<.001);assert.equal(m.health,.5);assert.equal(m.metres,Math.round(Math.hypot(e.x-own.x,e.y-own.y)/16));}
 assert.equal(enemyIndicator(camera,{...camera,hp:9000,maxHP:9000},own),null);assert.equal(enemyIndicator(camera,{x:2700,y:800,hp:0,maxHP:9000},own),null);
});
test('a contested resource needs control; clearing defenders awards one buff and retires the objective',async()=>{
 const {updateObjectives}=await import('../modules/pixel-war/strategy.mjs'),w=new PixelWorld();w.units=[];w.nextObjective=1e9;const o={id:'fixture-objective',kind:'warhorn',x:1536,y:896,readyAt:0,until:40000,progress:{demon:0,human:0},claimedBy:null};w.objectives=[o];Object.assign(w.heroes.demon,{x:1401,y:896});Object.assign(w.heroes.human,{x:1671,y:896});const a=w.fighter('demon','shield',UNITS.shield,1490,896),b=w.fighter('human','shield',UNITS.shield,1580,896);w.units=[a,b];
 for(let i=0;i<100;i++){w.time+=50;updateObjectives(w,50);}assert(o.contested);assert.equal(o.claimedBy,null);assert.equal(w.strategyStats.contested,1);
 b.hp=0;for(let i=0;i<50;i++){w.time+=50;updateObjectives(w,50);}assert.equal(o.claimedBy,'demon');assert.equal(w.strategyStats.claims.demon,1);assert.equal(w.battleBuffs.demon,w.time+14000);
 const basic=rawDamage(a,b);assert(Math.abs(rawDamage({...a,empowered:true},b)-basic*1.25)<1e-9);w.time+=5000;updateObjectives(w,50);assert.equal(w.objectives.length,0);assert.equal(w.strategyStats.claims.demon,1);
});
test('an injured commander seeks a usable pickup; retreat orders override an objective and movement stays visible',async()=>{
 const {commanderPlan}=await import('../modules/pixel-war/strategy.mjs'),w=new PixelWorld(),h=w.heroes.demon;h.hp=4000;w.pickups=[{id:1,kind:'heal',x:h.x+100,y:h.y,until:20000}];const plan=commanderPlan(w,h,[],[]);assert.equal(plan.order,'resupply');const before=h.hp;advance(w,1600);assert(h.hp>before);assert(!w.pickups.some(p=>p.id===1&&!p.used));w.command('demon','retreat',0);const retreat=commanderPlan(w,h,[],[]);assert.equal(retreat.order,'retreat');assert(retreat.goal.x<h.x);const camera=cameraTarget(w.snapshot(),'demon');assert(Math.abs(camera.x-h.x)<=260);assert(Math.abs(camera.y-h.y)<=130);
});
