import {mockPack} from './fixtures/luna-pack.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {launchOwnedEvent,updateOwnedEvents} from '../modules/pixel-war/owned-events.mjs';
import {buildBarracks,updateBarracks} from '../modules/pixel-war/barracks.mjs';
import {tickWarDrama} from '../modules/pixel-war/war-drama.mjs';
import {updateEncounters} from '../modules/pixel-war/encounters.mjs';
import {beginSettlement,advanceSettlement,holdBattleClocks} from '../modules/pixel-war/settlement.mjs';
import {createPreview} from '../modules/duel-preview/server.mjs';
import {giftEntitlement} from '../modules/pixel-war/public/gift-tiers.mjs';
import {resolveGiftMapping} from '../modules/live-runtime/gift-catalog.mjs';
const tick=(g,ms)=>{for(let i=0;i<ms;i+=50)g.step(50);};
const grant=(side='demon',id='one')=>({side,receipt:'test:'+id,source:'test',supporter:{id,name:'玩家'+id,platform:'test'}});
test('only generated opening plays; first deployment queues a genuine intervention without receipt replay',()=>{const g=new LiveGame();try{
 mockPack(g.world,'demon',{opening:'测试开场甲',help_accuse:'测试援军反应甲'});mockPack(g.world,'human',{opening_reply:'测试开场乙',help_boast:'测试援军反应乙'});
 tick(g,11000);assert.deepEqual(g.world.lunaSpeech.history.filter(e=>e.cue.startsWith('opening')).map(e=>e.side),['demon','human']);assert(g.world.speech.every(e=>e.model==='gpt-5.6-luna'));
 g.world.paused=true;g.testChat({side:'human',text:'参战',id:'test:first'});assert(!g.world.lunaSpeech.pending.some(q=>q.cue==='help_accuse'));g.world.paused=false;tick(g,11000);
 const replies=g.world.lunaSpeech.history.filter(e=>e.cue.startsWith('help_'));assert.deepEqual(replies.map(e=>e.side),['demon','human']);assert.equal(replies[0].text,'测试援军反应甲');g.testChat({side:'human',text:'参战',id:'test:first'});tick(g,5000);assert.equal(g.world.lunaSpeech.history.filter(e=>e.cue.startsWith('help_')).length,2);
 }finally{g.close();}});
test('barracks is a durable owned attackable building; troops emerge at its door with matching owner and service, destruction stops production',async()=>{const dir=await mkdtemp(join(tmpdir(),'duel-barracks-'));let g=new LiveGame({path:join(dir,'state.sqlite')});try{g.testGift({side:'demon',reward:'barracks',viewer:'viewer-c',id:'test:building'});g.drain();const b=g.world.barracks[0],h=g.world.heroes.demon;assert(b&&b.x<h.x-400);assert.equal(b.supporter.name,'试玩丙');assert(g.world.allAlive().includes(b));assert.equal(g.world.units.length,0);g.world.time=b.nextProduceAt;updateBarracks(g.world);const u=g.world.units[0];assert.equal(u.barracksId,b.id);assert.equal(u.supporter.id,b.supporter.id);assert.deepEqual(u.service,b.service);assert(Math.hypot(u.x-b.x,u.y-b.y)<220);assert(u.maxHP>1000);const id=b.id,reserve=b.reserve;g.close();g=new LiveGame({path:join(dir,'state.sqlite')});assert.equal(g.world.barracks[0].id,id);assert.equal(g.world.barracks[0].reserve,reserve);g.testGift({side:'demon',reward:'barracks',id:'test:building'});assert.equal(g.world.barracks.length,1);g.world.resolveHit(g.world.heroes.human,g.world.barracks[0],1e9);const produced=g.world.barracks[0].produced;g.world.time+=7000;updateBarracks(g.world);assert.equal(g.world.barracks[0].produced,produced);assert(!g.world.fallenTroops.some(f=>f.kind==='barracks'));}finally{g.close();await rm(dir,{recursive:true,force:true});}});
test('production is bounded, waits for capacity without losing reserve, and preserves the barracks and its troops across generations',()=>{const g=new LiveGame();try{const w=g.world,bg=grant();assert(buildBarracks(w,bg));const b=w.barracks[0];w.population=()=>600;w.time=3000;updateBarracks(w);assert.equal(b.reserve,36);assert.equal(w.units.length,0);delete w.population;for(let i=0;i<40;i++){w.time+=7000;w.deployed.demon=[];updateBarracks(w);}assert.equal(w.units.length,12);assert.equal(b.reserve,24);for(const u of w.units)u.hp=0;w.time+=7000;updateBarracks(w);assert.equal(b.reserve,23);assert(w.units.at(-1).service.expiresAtDeath===null);w.leaderDeaths=30;b.hp=2000;updateBarracks(w);assert.equal(w.barracks.length,1);assert.equal(b.hp,2000);}finally{g.close();}});
test('nine-region meteor barrage aims at enemy, gives warnings, deals real friendly fire and credits only enemy damage to sponsor',()=>{const g=new LiveGame();try{const w=g.world;w.mode='test_live';assert(launchOwnedEvent(w,grant(),'meteorstorm'));const e=w.warEvents[0],hazards=w.hazards.filter(h=>h.eventId===e.id);assert.equal(hazards.length,9);assert(new Set(hazards.map(h=>h.x+','+h.y)).size===9);assert(Math.abs(e.x-w.heroes.human.x)<1);const hit=hazards[0];Object.assign(w.heroes.demon,{x:hit.x,y:hit.y,hp:9000});Object.assign(w.heroes.human,{x:hit.x+5,y:hit.y,hp:9000});w.time=hit.impact;const pending=[];updateEncounters(w,w.allAlive(),pending);for(const p of pending)w.resolveHit(...p);assert(w.heroes.demon.hp<9000);assert(w.heroes.human.hp<9000);const honors=Object.values(w.honors.entries);assert.equal(honors.length,1);assert.equal(honors[0].name,'玩家one');assert.equal(honors[0].damage,9000-w.heroes.human.hp);assert(Object.keys(w.terrainChanges).length>0);assert.equal(w.announcements.at(-1).owner.id,'one');}finally{g.close();}});
test('sponsored neutral beasts enter from the north after a warning, can attack either side, and never enter troop resurrection',()=>{const g=new LiveGame();try{const w=g.world;assert(launchOwnedEvent(w,grant(),'beastRaid'));assert.equal(w.wildlife.length,0);w.time=w.warEvents[0].impact;updateOwnedEvents(w);assert.equal(w.wildlife.length,12);assert(w.wildlife.every(u=>u.y<0&&u.stampede&&u.sponsorSide==='demon'&&u.side==='neutral'&&u.supporter.id==='one'));const beast=w.wildlife[0];w.resolveHit(beast,w.heroes.human,100);assert(Object.values(w.honors.entries).some(e=>e.side==='demon'&&e.name==='玩家one'));const before=Object.values(w.honors.entries)[0].damage;w.resolveHit(beast,w.heroes.demon,100);assert.equal(Object.values(w.honors.entries)[0].damage,before);w.resolveHit(w.heroes.human,beast,1e8);assert(!w.fallenTroops.some(f=>f.id===beast.id));}finally{g.close();}});
test('all surprise types are funded, concurrent events queue durably, and settlement freezes production and event clocks',()=>{const g=new LiveGame();try{const w=g.world;for(const key of ['rift','tempest','supplyDrop']){assert(launchOwnedEvent(w,grant('demon',key),key));}assert.equal(launchOwnedEvent(w,grant(),'bloodrite'),false);g.testGift({side:'human',reward:'bloodrite',id:'test:queued-event'});g.drain();assert(g.meta.queue.some(q=>q.receipt==='test:queued-event'));buildBarracks(w,grant());const due=w.barracks[0].nextProduceAt,until=w.warEvents[0].until;holdBattleClocks(w,2000);assert.equal(w.barracks[0].nextProduceAt,due+2000);assert.equal(w.warEvents[0].until,until+2000);w.time=25000;updateOwnedEvents(w);g.drain();assert(w.warEvents.some(e=>e.key==='bloodrite'&&e.actorSide==='human'));assert(!g.meta.queue.some(q=>q.receipt==='test:queued-event'));}finally{g.close();}});
test('premium catalog game mappings agree between advertised menu and receipt; free bag copies cannot unlock premium events',()=>{const g=new LiveGame();try{for(const [name,key] of [['bilibili世界','barracks'],['私人飞机','fortress'],['星轨列车','fortress']]){assert.equal(giftEntitlement({name,price:500000,coinType:'gold'}).reward,key);assert.notEqual(giftEntitlement({name,price:500000,coinType:'silver'}).reward,key);}assert.equal(resolveGiftMapping(g,{platform:'bilibili',giftId:987654321,quantity:1,paid:true}),null);}finally{g.close();}});
test('owner HTTP gift endpoint assigns event ownership and deduplicates; broadcast and unowned action endpoints cannot launch it',async()=>{const app=await createPreview({stagePort:19980,controlPort:19981,clock:false});try{const base='http://127.0.0.1:19981',html=await(await fetch(base)).text(),token=html.match(/name="owner-token" content="([^"]+)/)[1],headers={'Content-Type':'application/json',Origin:base,'X-Owner-Token':token},body=JSON.stringify({side:'human',reward:'meteorstorm',viewer:'viewer-c',id:'test:http-owned'});assert.equal((await fetch(base+'/owner/gift',{method:'POST',headers,body})).status,200);app.game.drain();assert.equal(app.world.warEvents[0].owner.name,'试玩丙');await fetch(base+'/owner/gift',{method:'POST',headers,body});app.game.drain();assert.equal(app.world.warEvents.length,1);assert.equal((await fetch('http://127.0.0.1:19980/owner/gift',{method:'POST',headers,body})).status,405);assert.equal((await fetch(base+'/action',{method:'POST',headers,body:JSON.stringify({type:'disaster',disaster:'meteor'})})).status,400);}finally{await app.close();}});

test('player army attacks an enemy barracks through the ordinary combat loop; revived veterans retain their producing barracks',()=>{const g=new LiveGame();try{const w=g.world;buildBarracks(w,grant());const b=w.barracks[0];b.nextProduceAt=1e8;for(const h of Object.values(w.heroes))h.stunnedUntil=1e8;assert(w.spawn('human','musketeer',1,false,grant('human','raider')));const u=w.units.at(-1);Object.assign(u,{x:b.x+100,y:b.y,targetId:b.id,readyAt:0});const hp=b.hp;tick(g,7000);assert(b.hp<hp,'nearby player soldier should damage the building without a direct resolveHit call');b.nextProduceAt=w.time;updateBarracks(w);const soldier=w.units.find(u=>u.barracksId===b.id);assert(soldier);w.resolveHit(u,soldier,1e8);const fallen=w.fallenTroops.find(f=>f.id===soldier.id);assert.equal(fallen.barracksId,b.id);assert(w.spawn('demon',soldier.kind,1,false,{...grant(),reviveId:soldier.id}));assert.equal(w.units.find(v=>v.id===soldier.id).barracksId,b.id);}finally{g.close();}});

test('gift barrage persists once across restart and its character response names the actual intervention',async()=>{const dir=await mkdtemp(join(tmpdir(),'duel-owned-event-'));let g=new LiveGame({path:join(dir,'state.sqlite')});try{g.testGift({side:'human',reward:'meteorstorm',id:'test:durable-barrage'});tick(g,1400);const id=g.world.warEvents[0].id;assert(g.world.lunaSpeech.pending.some(l=>l.facts?.reward==='meteorstorm'));assert.equal(g.world.speech.length,0);g.close();g=new LiveGame({path:join(dir,'state.sqlite')});assert.equal(g.world.warEvents[0].id,id);g.testGift({side:'human',reward:'meteorstorm',id:'test:durable-barrage'});g.drain();assert.equal(g.world.warEvents.length,1);assert.equal(g.world.hazards.filter(h=>h.eventId===id).length,9);}finally{g.close();await rm(dir,{recursive:true,force:true});}});

test('late voice completion cannot replay an expired taunt over the following speaker',async()=>{let release,started=false,finished=false;const broker={status:{models:{enabled:false},voice:{enabled:true}},poll:async()=>{},request:async path=>{if(path==='/voice'&&!started){started=true;return await new Promise(r=>{release=r;});}return {ok:false};}};const app=await createPreview({stagePort:19974,controlPort:19975,clock:false,broker});try{app.game.runtime.voiceEnabled=true;mockPack(app.world,'demon');mockPack(app.world,'human');tick(app.game,1400);const first=app.world.speech.find(s=>s.duologue);for(let i=0;i<100&&!started;i++)await new Promise(r=>setTimeout(r,25));assert(started);app.world.time=first.until+500;tickWarDrama(app.world,{voice:true});const second=app.world.speech.at(-1);assert.notEqual(second.id,first.id);release({ok:true,wav:Buffer.alloc(44).toString('base64')});finished=true;await new Promise(r=>setTimeout(r,30));assert.equal(first.audioUrl,undefined);assert.equal(first.audioMode,'subtitle_only');assert.equal(app.world.warDrama.speaking,second.id);assert.equal(app.world.speech.at(-1).id,second.id);}finally{if(release&&!finished)release({ok:false});await app.close();}});
