import test from 'node:test';import assert from 'node:assert/strict';
import {PixelWorld} from '../modules/pixel-war/world.mjs';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {UNITS,ACTIONS} from '../modules/pixel-war/public/catalog.mjs';
import {SpatialGrid} from '../modules/pixel-war/public/spatial.mjs';
import {releaseProjectiles,projectileImpact} from '../modules/pixel-war/ordnance.mjs';
import {combatFocus,reserveEffects} from '../modules/pixel-war/public/combat-focus.mjs';
import {weaponMuzzle} from '../modules/pixel-war/public/weapon-geometry.mjs';
import {CombatEffects} from '../modules/pixel-war/public/effects.mjs';
import {PlayerCombatEffects,shotPoint,damageSlot} from '../modules/pixel-war/public/player-combat-fx.mjs';
import {encodeFrame,decodeFrame} from '../modules/pixel-war/public/wire.mjs';
import {combatSkill,updateEncounters} from '../modules/pixel-war/encounters.mjs';
import {lightBarrels,ensureFieldProps,updateFieldProps} from '../modules/pixel-war/field-props.mjs';
import {supporterGuides} from '../modules/pixel-war/public/supporter-guides.mjs';
const viewer={id:'viewer-a',name:'玩家甲',platform:'test'};
function fixture(kind='musketeer'){const w=new PixelWorld();w.units=[];w.events=[];w.missiles=[];const u=w.fighter('human',kind,UNITS[kind],10800,1152),t=w.fighter('demon','shield',UNITS.shield,11000,1152);Object.assign(u,{source:'test',supporter:viewer,life:2,face:0,giftQuality:{tier:5}});w.units.push(u,t);return {w,u,t};}
function release(w,u,t){const a={type:UNITS[u.kind].action,angle:Math.atan2(t.y-u.y,t.x-u.x),contactAt:w.time,critical:true};u.action=a;releaseProjectiles(w,u,t,a,new SpatialGrid([u,t]),ACTIONS[a.type].projectile);return w.missiles;}
test('all ranged player weapons retain owner, life, per-shot release and impact through wire snapshots',()=>{for(const [kind,spec]of Object.entries(UNITS)){if(!ACTIONS[spec.action]?.projectile)continue;const {w,u,t}=fixture(kind),missiles=release(w,u,t);assert.equal(w.events.filter(e=>e.type==='release').length,u.shots||1,kind);const frame=decodeFrame(JSON.parse(JSON.stringify(encodeFrame(w.snapshot()))));for(const m of frame.missiles){assert.equal(m.focus.ownerId,viewer.id);assert.equal(m.focus.life,2);assert(m.from&&m.physicalFrom);}for(const m of missiles){w.time=m.born+150;const pending=[];projectileImpact(w,m,t,new SpatialGrid([t]),pending);for(const hit of pending)w.resolveHit(...hit);assert(w.events.some(e=>e.type==='shot_end'&&e.shotId===m.id&&e.focus.ownerId===viewer.id));}assert(w.events.some(e=>e.type==='hit'&&e.focus.ownerId===viewer.id),kind);}});
test('visual events cannot alter gameplay IDs or the random stream',()=>{const a=new PixelWorld(37),b=new PixelWorld(37);for(let i=0;i<500;i++)a.emitVisual('windup',{focus:{unitId:'u',life:1},x:0,y:0});assert.equal(a.serial,b.serial);assert.equal(a.seed,b.seed);assert.equal(a.fighter('human','militia',UNITS.militia,10800,1152).id,b.fighter('human','militia',UNITS.militia,10800,1152).id);});
test('muzzles are attached to the hand barrel and both rotated machine barrels',()=>{const {u}=fixture();u.x=u.y=0;u.face=0;const p=weaponMuzzle(u);assert.deepEqual(p,{x:52,y:0,z:25});const machine={...u,kind:'dreadnought',machine:true,scale:3.2,face:Math.PI/2,action:{contactAt:0}},a=weaponMuzzle(machine,Math.PI/2,0,0),b=weaponMuzzle(machine,Math.PI/2,1,0);assert(Math.abs(a.x-b.x-64)<1e-6);assert(Math.abs(a.y-42*3.2)<1e-6);assert.equal(a.z,56*3.2);});
test('NPC event storms never evict player release, impact or damage events',()=>{const {w,u}=fixture();for(let i=0;i<80;i++)w.emitVisual('hit',{x:10800,y:1152,amount:23,focus:{...combatFocus(u),unitId:'u'+i,ownerId:'p'+i}});for(let i=0;i<3000;i++)w.emit('hit',{x:10800,y:1152,amount:9});assert.equal(w.events.filter(e=>e.focus).length,80);assert.equal(w.events.filter(e=>!e.focus).length,180);const fx=new CombatEffects();fx.consume(w.snapshot());assert.equal(fx.player.events.length,80);assert.equal(fx.player.numberGroups(0,{side:'human',visible:()=>true}).length,80);fx.consume(w.snapshot());assert.equal(fx.player.events.length,80);});
test('very short completed flights remain visible in order; misses do not create damage',()=>{const fx=new PlayerCombatEffects(),focus={ownerId:'a',unitId:'u',life:1,side:'human',color:'#a6e9b0'},e={id:1,type:'release',at:100,shotId:20,focus,x:0,y:0,z:25,from:{x:0,y:0,z:25},targetX:20,targetY:0,targetZ:25,flight:25,style:'bullet'},end={id:2,type:'shot_end',at:125,shotId:20,focus,x:20,y:0,z:25,reason:'hit'};fx.add(e);fx.add(end);fx.add({id:3,type:'hit',at:125,shotId:20,focus,x:20,y:0,amount:50});assert.equal(shotPoint(fx.shots.get(20),null,99),null);const p=shotPoint(fx.shots.get(20),null,170);assert(p.x>0&&p.x<20);assert.equal(fx.effectAt(fx.events[2]),240);assert.equal(shotPoint(fx.shots.get(20),null,241),null);fx.prune(2000);assert.equal(fx.shots.size,0);const missed=new PlayerCombatEffects();missed.add(e);missed.add({...end,reason:'lost'});assert.equal(missed.numberGroups(300,{visible:()=>true}).length,0);});
test('projectile and giant skill credits survive attacker death without crediting a revived life',()=>{const {w,u,t}=fixture('colossus');u.x=t.x-100;assert(combatSkill(w,u,[t]));const h=w.hazards.at(-1);u.hp=0;w.units=[t];w.time=h.impact;const pending=[];updateEncounters(w,[t],pending);assert(w.events.some(e=>e.type==='slam'&&e.focus?.life===2));assert.equal(pending[0][0].supporter.id,viewer.id);assert.equal(pending[0][0].life,2);const g=new LiveGame();try{g.world.missiles=release(w,{...u,hp:1,kind:'musketeer',...UNITS.musketeer,source:'test',supporter:viewer,life:2},t);const saved=g.capture();g.restore(saved);assert.equal(g.world.missiles[0].focus.life,2);}finally{g.close();}});
test('player-ignited barrel retains ownership after source removal and into chained blasts',()=>{const {w,u}=fixture('cannon'),p=ensureFieldProps(w).items.find(p=>p.kind==='barrel');Object.assign(u,{x:p.x-180,y:p.y});lightBarrels(w,p,u,10);w.units=[];w.time=p.fuseAt;updateFieldProps(w);assert(w.events.some(e=>e.type==='explosion'&&e.style==='powder'&&e.focus?.ownerId===viewer.id));});
test('every melee weapon starts an owned readable attack and offscreen armies advertise active attacks',()=>{for(const [kind,spec]of Object.entries(UNITS)){if(ACTIONS[spec.action]?.projectile)continue;const {w,u,t}=fixture(kind);w.attack(u,t);assert.equal(w.events.find(e=>e.type==='windup').focus.ownerId,viewer.id);const c={x:0,y:0,screenW:960,screenH:540,project:()=>({x:2000,y:0})};assert.equal(supporterGuides([u],c,'human')[0].firing,true);}});
test('reconnecting mid-flight restores player tracers from authoritative missile data without inventing hits',()=>{const {w,u,t}=fixture('cannon');release(w,u,t);w.time=1200;const snapshot=w.snapshot();snapshot.events=[];const fx=new CombatEffects();fx.consume(snapshot);assert.equal(fx.player.shots.size,1);assert.equal(fx.player.numberGroups(1200,{visible:()=>true}).length,0);const shot=[...fx.player.shots.values()][0];assert.equal(shot.release.from.x,snapshot.missiles[0].from.x);assert.equal(shot.release.focus.ownerId,viewer.id);});

test('crowded damage totals merge per viewer without losing any viewer or inflating damage',()=>{const fx=new PlayerCombatEffects();for(let owner=0;owner<12;owner++)for(let i=0;i<9;i++)fx.add({id:owner*9+i,type:'hit',at:i*100,x:500+i*30,y:500,amount:10,focus:{unitId:'u'+i,ownerId:'p'+owner,side:'human'}});const groups=fx.numberGroups(1000,{side:'human',visible:()=>true});assert.equal(groups.length,12);assert.equal(new Set(groups.map(g=>g.focus.ownerId)).size,12);for(const g of groups){assert.equal(g.amount,90);assert.equal(g.count,9);}assert.equal(fx.events.length,108);});

test('dense viewer numbers find vacant ground instead of stacking on a blocked battle',()=>{const camera={screenW:744,screenH:562},blocked=[{x:200,y:0,w:420,h:260},{x:0,y:0,w:210,h:100},{x:530,y:365,w:214,h:197}];for(let i=0;i<12;i++){const b=damageSlot({x:500,y:120},74,35,blocked,camera,true);assert(b,'viewer '+i+' gets a distinct slot');assert(!blocked.some(a=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y));blocked.push(b);}});

test('owned meteor and quake impacts reach the blast renderer after routing into the player effect budget',()=>{const previous=globalThis.document,ops=[];const c=new Proxy({},{get:(_,key)=>key==='measureText'?()=>({width:20}):(...args)=>ops.push([key,...args]),set:()=>true});globalThis.document={createElement:()=>({getContext:()=>c})};try{for(const type of ['meteor','quake']){ops.length=0;const fx=new PlayerCombatEffects();fx.add({id:1,type,at:100,x:500,y:500,radius:215,focus:{unitId:'gift',ownerId:'player',side:'human',life:1,color:'#89e3dc',tier:6}});fx.draw(c,{missiles:[]},[],400,{side:'human',zoom:.66,visible:()=>true});assert.equal(fx.stats.explosions,1);assert(fx.stats.activeOwners.includes('player'));assert(ops.some(op=>op[0]==='drawImage'));}}finally{globalThis.document=previous;}});
