import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {runtimeAvailability} from '../modules/live-runtime/availability.mjs';
import {launchReadiness} from '../modules/live-runtime/readiness.mjs';
import {tickAudience,audienceState,audienceModelFailed} from '../modules/live-runtime/audience.mjs';
import {CharacterVoice} from '../modules/live-runtime/tts.mjs';
import {createPreview} from '../modules/duel-preview/server.mjs';
import {LocalVoice} from '../modules/local-voice/service.mjs';
test('memory pressure blocks local voice before a worker is spawned and is reflected in runtime readiness',async()=>{const v=new LocalVoice({memoryProbe:()=>false});v.available=true;v.start=()=>{throw Error('must not load a model under pressure');};assert.equal((await v.speak({side:'demon',text:'收到，我会撤退。',rank:0})).reason,'local_voice_memory_pressure');assert(!v.child);assert(!runtimeAvailability({voice:{enabled:true,configured:true,local:v.status()}}).voiceEnabled);v.stop();});
test('validated generated audience response reaches the voice endpoint and playable stage audio without spending a model call',async()=>{let spoken;const wav=Buffer.alloc(44+4800);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(24000,24);wav.writeUInt32LE(48000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(4800,40);
 const broker={status:{models:{enabled:true,transport:'codex',authenticated:true,dayCalls:600,dayLimitCalls:600},voice:{enabled:true,configured:true,provider:'local'}},poll:async()=>{},request:async(path,data)=>{assert.notEqual(path,'/decision');if(path==='/voice'){spoken=data;return {ok:true,wav:wav.toString('base64')};}return {ok:true};}};
 const app=await createPreview({stagePort:19888,controlPort:19889,clock:false,broker});try{await new Promise(r=>setTimeout(r,1050));app.game.runtime.modelEnabled=true;app.game.testChat({side:'demon',text:'首领后退'});app.game.step(50);const context=app.game.context('demon');assert(app.game.applyDecision(context,{strategy:'auto',tactic:'hold',lane:1,speech:'行，先往后撤。',memory:'',replyTo:context.audience.selected.id,audienceAction:'retreat'},'gpt-5.6-luna'));for(let n=0;n<25&&!app.world.speech.some(s=>s.audioUrl);n++)await new Promise(r=>setTimeout(r,100));const line=app.world.speech.find(s=>s.audioUrl);assert(line);assert.equal(line.audioMode,'full_read');assert.equal(spoken.text,line.text);assert(spoken.text.includes(line.text));const r=await fetch('http://127.0.0.1:19888'+line.audioUrl);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'audio/wav');assert.equal((await r.arrayBuffer()).byteLength,wav.length);assert.equal(app.world.heroes.demon.viewerAdvice.kind,'retreat');}finally{await app.close();}});
test('enabled but quota-blocked model stays unanswered without executing advice and quota recovery remains possible',()=>{const g=new LiveGame();try{const blocked={models:{enabled:true,transport:'codex',authenticated:true,state:'subscription_call_limit',dayCalls:600,dayLimitCalls:600}};g.runtime=runtimeAvailability(blocked);assert(!g.runtime.modelEnabled);g.testChat({side:'demon',text:'首领撤退'});tickAudience(g);assert.equal(audienceState(g).active.demon.phase,'unanswered');assert(!g.world.heroes.demon.viewerAdvice);assert.equal(g.world.speech.length,0);blocked.models.dayCalls=599;assert(runtimeAvailability(blocked).modelEnabled);assert(!runtimeAvailability({...blocked,unavailable:true}).modelEnabled);}finally{g.close();}});
test('failed model request stays unanswered at the next game tick and stale failure cannot retire a newer message',()=>{const g=new LiveGame();try{g.runtime.modelEnabled=true;g.testChat({side:'human',text:'皇冠歪了'});tickAudience(g);const m=audienceState(g).active.human;assert.equal(m.phase,'waiting_model');assert(!audienceModelFailed(g,'human','wrong','timeout'));assert(audienceModelFailed(g,'human',m.id,'timeout'));tickAudience(g);assert.equal(m.phase,'unanswered');assert.equal(m.replyMode,'none');assert(!audienceModelFailed(g,'human',m.id,'timeout'));assert.equal(g.world.speech.length,0);}finally{g.close();}});
test('local voice sends only text data, enforces shared character budgets, and never needs a cloud key',async()=>{const db=new DatabaseSync(':memory:'),cfg={enabled:true,provider:'local',hourCharacters:12,dayCharacters:24};let calls=0;const wav=Buffer.alloc(44);wav.write('RIFF');wav.write('WAVE',8);const voice=new CharacterVoice({db,config:()=>cfg,fetcher:()=>{throw Error('cloud must not be used');},localRequest:async r=>{calls++;assert.deepEqual(Object.keys(r).sort(),['rank','side','text']);return {ok:true,wav:wav.toString('base64')};}});try{assert((await voice.speak({side:'demon',text:'观众说后退，我收到了',rank:0})).ok);assert.equal((await voice.speak({side:'demon',text:'这句话超过剩余预算',rank:0})).reason,'character_budget_limit');assert.equal(calls,1);}finally{voice.stop();db.close();}});
test('readiness does not equate a login, a mapped gift, or an enabled toggle with verified streaming',()=>{const g=new LiveGame();try{const r=launchReadiness(g,{models:{enabled:true,authenticated:true,state:'ready'},bilibili:{configured:true,state:'authenticated',accepted:5},voice:{enabled:true,configured:true,provider:'local'}});assert(r.localPlayable);assert(!r.platformPlayReady);assert(!r.bilibili.authorizedRoundTripVerified);assert(!r.streamingVerified);assert(!r.xiaohongshu.connected);assert(r.voice.fullReadAvailable);}finally{g.close();}});
test('HTTP integration treats blocked broker capability as unavailable rather than waiting 45 seconds or spending another call',async()=>{let calls=0;const broker={status:{models:{enabled:true,transport:'codex',authenticated:true,dayCalls:600,dayLimitCalls:600,state:'subscription_call_limit'},voice:{enabled:false}},poll:async()=>{},request:async(path)=>{if(path==='/decision')calls++;return {ok:true};}};const app=await createPreview({stagePort:19886,controlPort:19887,clock:false,broker});try{await new Promise(r=>setTimeout(r,1150));app.game.testChat({side:'demon',text:'首领后退'});app.game.step(50);assert.equal(app.game.runtime.modelEnabled,false);assert.equal(audienceState(app.game).active.demon.phase,'unanswered');assert.equal(calls,0);}finally{await app.close();}});
test('failed local synthesis cannot consume the successful speech allowance',async()=>{
 const db=new DatabaseSync(':memory:');const voice=new CharacterVoice({db,config:()=>({enabled:true,provider:'local',hourCharacters:12,dayCharacters:24}),localRequest:async()=>({ok:false,reason:'local_voice_failed'})});
 try{await voice.speak({side:'empress',text:'桥头又开打了。'});assert.equal(voice.usage().dayCharacters,0);}finally{voice.stop();db.close();}
});
