import test from 'node:test';
import assert from 'node:assert/strict';
import {SpeechPlayback} from '../modules/pixel-war/public/speech-playback.mjs';
function fixture(){let now=0;const audios=[];const p=new SpeechPlayback({now:()=>now,createAudio:url=>{const a={url,paused:true,ended:false,currentTime:0,play(){this.paused=false;return Promise.resolve();},pause(){this.paused=true;this.onpause?.();},playing(){this.paused=false;this.onplaying?.();},end(){this.ended=true;this.paused=true;this.onended?.();}};audios.push(a);return a;}});const state={time:1000,fieldEpoch:1,heroes:{human:{id:'h',hp:100},demon:{id:'d',hp:100}},speech:[]};const line=(id,side='demon')=>({id,side,persona:side==='demon'?'d':'h',text:'测试语音 '+id,at:1000,until:10000,audioUrl:'/voice/'+id+'.wav'});return {p,state,audios,line,time:v=>now=v};}
test('a synthesized line cannot show early; next clip waits for actual ended across both factions',async()=>{const {p,state,audios,line}=fixture();state.speech=[line(1),line(2,'human')];p.update(state,{enabled:true});assert.equal(audios.length,2);assert(audios[1].paused,'next clip is preloaded, never played early');assert.equal(p.presentation('demon'),null);audios[0].playing();assert.equal(p.presentation('demon').id,1);state.time=20000;p.update(state,{enabled:true});assert.equal(p.presentation('demon').id,1,'server deadline cannot cut off a buffered voice');assert.equal(audios.length,2);assert(audios[1].paused);audios[0].end();assert.equal(audios.length,2);assert.equal(p.presentation('human'),null);audios[1].playing();assert.equal(p.presentation('human').id,2);audios[1].end();assert.equal(p.presentation('human'),null);});
test('model/TTS pending text does not enter the audio queue',()=>{const {p,state,line}=fixture();state.speech=[{...line(1),audioUrl:null,audioMode:'synthesizing'}];p.update(state,{enabled:true});assert.equal(p.status().queued,0);assert.equal(p.presentation('demon'),null);state.speech[0].audioUrl='/voice/1.wav';p.update(state,{enabled:true});assert.equal(p.status().lineId,1);});
test('pause/mute/buffering hide the same subtitle and resume at the media clock',async()=>{const {p,state,audios,line}=fixture();state.speech=[line(1)];p.update(state,{enabled:true});await Promise.resolve();audios[0].playing();audios[0].currentTime=2;p.update(state,{enabled:false});assert.equal(p.presentation('demon'),null);p.update(state,{enabled:true});audios[0].playing();assert.equal(p.presentation('demon').at,-1000);audios[0].onwaiting();assert.equal(p.presentation('demon'),null);audios[0].playing();p.update(state,{enabled:true,paused:true});assert.equal(p.presentation('demon'),null);});
test('a new server audience turn does not interrupt the playing clip; dead/reset personas do',()=>{const {p,state,audios,line}=fixture();state.speech=[{...line(1),audienceId:'first'}];p.update(state,{enabled:true});audios[0].playing();state.audience={active:{demon:{id:'next'}}};p.update(state,{enabled:true});assert.equal(p.presentation('demon').id,1);state.heroes.demon.id='new';p.update(state,{enabled:true});assert.equal(p.presentation('demon'),null);assert(audios[0].paused);state.fieldEpoch=2;p.update(state,{enabled:true});assert.equal(p.status().queued,0);});
test('network failure advances safely; a stalled clip has a bounded timeout',()=>{const {p,state,audios,line,time}=fixture();state.speech=[line(1),line(2)];p.update(state,{enabled:true});audios[0].onerror();assert.equal(p.status().lineId,2);time(16000);assert.equal(p.presentation('demon'),null);assert.equal(p.status().errors,2);assert.equal(p.status().lineId,null);});
test('autoplay rejection keeps the current clip retryable after a real user gesture',async()=>{const {p,state,audios,line}=fixture();let blocked=false;p.onBlocked=()=>blocked=true;p.createAudio=url=>{const a={url,paused:true,play:()=>Promise.reject({name:'NotAllowedError'}),pause(){}};audios.push(a);return a;};state.speech=[line(1)];p.update(state,{enabled:true});await new Promise(r=>setImmediate(r));assert(blocked);assert.equal(p.status().lineId,1);assert.equal(p.presentation('demon'),null);audios[0].play=()=>{audios[0].paused=false;audios[0].onplaying();return Promise.resolve();};p.update(state,{enabled:true});assert.equal(p.presentation('demon').id,1);});

test('withdrawal revokes queued and already playing audience lines',()=>{const {p,state,audios,line}=fixture();state.speech=[{...line(1),audienceId:'a'},{...line(2),audienceId:'b'}];p.update(state,{enabled:true});audios[0].playing();state.audience={revoked:['a','b']};p.update(state,{enabled:true});assert.equal(p.presentation('demon'),null);assert.equal(p.status().queued,0);assert(audios[0].paused);});

import {leaderSpeechLayout} from '../modules/pixel-war/public/leader-speech.mjs';
test('a long viewer quote cannot push spoken words to a later page, including offscreen speakers',()=>{const {state,line}=fixture();const u={...state.heroes.demon,side:'demon',kind:'hero',name:'魔王',rank:0,x:2500,y:150},c={measureText:t=>({width:t.length*12})},camera={screenW:960,screenH:540,zoom:1,project:u=>({x:u.x,y:u.y})};const audio={...line(1),text:'先守桥口，别落单。',quote:{text:'你现在准备怎么打？'.repeat(20),supporter:{name:'支持者'}}};const box=leaderSpeechLayout(c,state,'demon',u,camera,[],audio);assert(box);assert(box.lines.join('').includes(audio.text));assert.equal(box.pages,1);assert(box.x>=0&&box.x+box.w<=960);assert.match(box.name,/魔族/);assert.equal(leaderSpeechLayout(c,state,'demon',u,camera,[],null),null);});
test('queued viewer reply plays before queued background after the current sentence',async()=>{
 const {p,state,audios,line}=fixture();state.speech=[line(1)];p.update(state,{enabled:true});audios[0].playing();
 state.speech.push(line(2,'human'),{...line(3),audienceId:'viewer-turn'});p.update(state,{enabled:true});assert.equal(p.status().lineId,1);
 audios[0].end();assert.equal(p.status().lineId,3);audios[1].playing();assert.equal(p.presentation('demon').audienceId,'viewer-turn');
 audios[1].end();assert.equal(p.status().lineId,2);
});

test('fresh narration preempts old unplayed clips and retains no more than two next audio candidates',()=>{
 const {p,state,audios,line,time}=fixture();state.audience={clock:100000,active:{demon:{id:'fresh'}}};state.speech=[line(1)];p.update(state,{enabled:true});audios[0].playing();
 state.speech=[line(2),line(3,'human'),{...line(4),audienceId:'old',deadline:100100},{...line(5),audienceId:'fresh',deadline:130000}];p.update(state,{enabled:true});assert(p.status().queued<=2);time(31000);audios[0].end();assert.notEqual(p.status().lineId,5);assert.notEqual(p.status().lineId,4);
});
test('subtitle-only fallback has a visible bounded presentation and matching receipts',()=>{
 const {p,state,line,time}=fixture(),receipts=[];p.onPresentation=(l,event)=>receipts.push({id:l.id,event});state.speech=[{...line(1),audioUrl:null,audioMode:'subtitle_only',audioDuration:4000}];p.update(state,{enabled:true});assert.equal(p.presentation('demon').id,1);assert.deepEqual(receipts,[{id:1,event:'started'}]);time(5000);p.update(state,{enabled:true});assert.equal(p.presentation('demon'),null);assert.equal(receipts[1].event,'ended');
});

test('TTS failure without audioDuration cannot leave a subtitle stuck and block future speech',()=>{const {p,state,line,time,audios}=fixture();state.speech=[{...line(1),audioUrl:null,audioMode:'subtitle_only'},line(2,'human')];p.update(state,{enabled:true});assert.equal(p.presentation('demon').id,1);time(10000);p.update(state,{enabled:true});assert.equal(p.status().lineId,2);audios[0].playing();assert.equal(p.presentation('human').id,2);assert.equal(p.presentation('demon'),null);});
