import test from 'node:test';
import assert from 'node:assert/strict';
import {PixelWorld} from '../modules/pixel-war/world.mjs';
import {LiveGame} from '../modules/live-runtime/game.mjs';
import {updateCampaign,campaignGoal,commandCampaign} from '../modules/pixel-war/campaign.mjs';
import {commanderPlan} from '../modules/pixel-war/strategy.mjs';
import {defenseStep} from '../modules/pixel-war/defense.mjs';
import {UNITS} from '../modules/pixel-war/public/catalog.mjs';
import {battleSignals} from '../modules/pixel-war/public/battle-signals.mjs';
import {eventTone,eventCaption} from '../modules/pixel-war/public/tactical-style.mjs';
import {tacticalMapLayout} from '../modules/pixel-war/public/tactical-map.mjs';
import {Camera} from '../modules/pixel-war/public/camera.mjs';
import {SiteCamera} from '../modules/pixel-war/public/site-camera.mjs';
import {modelRequest,validateDecision} from '../modules/live-runtime/models.mjs';
import {DecisionSchedule} from '../modules/live-runtime/decision-schedule.mjs';
import {holdBattleClocks} from '../modules/pixel-war/settlement.mjs';
function fixture(){const w=new PixelWorld();w.units=[];w.mode='test_live';w.nextSpawn=w.nextHazard=w.nextGiant=w.nextWildlife=w.nextObjective=w.nextSurprise=w.nextPickup=1e12;const s=w.campaign.sites.find(s=>s.owner==='demon'&&s.kind==='grain');Object.assign(w.heroes.demon,w.ground({x:s.x+900,y:s.y+100}));Object.assign(w.heroes.human,{x:s.x+1100,y:s.y+900});for(let i=0;i<12;i++)w.units.push(w.fighter('demon','militia',UNITS.militia,s.x+400+i*15,s.y+130));return {w,s};}
const attack=(w,s)=>{const u=w.fighter('human','militia',UNITS.militia,s.x-30,s.y+20);Object.assign(u,{x:s.x-30,y:s.y+20});w.units.push(u);return u;};
test('faction identity stays stable across mixed-audience viewpoints; neutral supply stays yellow',()=>{for(const kind of ['march','capture','frontline','assault']){const e={kind,actorSide:'human',defender:'demon',count:12};assert.equal(eventTone(e,'demon'),'neutral');assert.equal(eventTone(e,'human'),'neutral');}assert.equal(eventTone({kind:'supply'},'human'),'neutral');assert.equal(eventCaption({kind:'march',actorSide:'human',count:12},'demon'),'人族大军行进 ×12');});
test('a new siege alerts once, refreshes continuously, mobilizes a reserve and sends the commander to the real site',()=>{const {w,s}=fixture(),viewer=w.units[0];viewer.viewerOrder={kind:'advance',until:45000};const attacker=attack(w,s);w.time=50;updateCampaign(w,50);assert.equal(s.assault.defender,'demon');assert.equal(w.announcements.filter(e=>e.kind==='assault').length,1);assert.equal(w.campaign.responses.demon.siteId,s.id);assert(!viewer.defense);const guards=w.units.filter(u=>u.defense);assert(guards.length>=3&&guards.length<11);const goal=campaignGoal(w,guards[0]);assert.equal(goal.id,s.id);assert.equal(commanderPlan(w,w.heroes.demon,[attacker],w.units.filter(u=>u.side==='demon')).order,'defend');const start=Math.hypot(guards[0].x-goal.x,guards[0].y-goal.y);for(let i=0;i<30;i++){w.time+=50;updateCampaign(w,50);defenseStep(w,guards[0],null,campaignGoal(w,guards[0]),.05);}assert(Math.hypot(guards[0].x-goal.x,guards[0].y-goal.y)<start-20);assert.equal(w.announcements.filter(e=>e.kind==='assault').length,1);attacker.hp=0;w.time+=4000;updateCampaign(w,50);assert.equal(s.assault,null);assert.equal(w.campaign.responses.demon,undefined);assert(w.units.every(u=>!u.defense));});
test('a new attack supersedes an older model raid but not an explicit owner order',()=>{for(const source of ['model','owner']){const {w,s}=fixture();commandCampaign(w,'demon','raid_forge',{source});w.time+=1000;attack(w,s);updateCampaign(w,50);assert.equal(!!w.campaign.orders.demon,source==='owner');if(source==='model')assert(w.units.some(u=>u.defense));}});
test('marches and crossed swords reflect actual movement and attacks without fabricating an army',()=>{const base=Array.from({length:8},(_,i)=>({id:'u-'+i,side:'demon',hp:100,x:1000+i*15,y:900,moving:true,face:0,action:null}));let s=battleSignals({units:base});assert.equal(s.marches[0].count,8);assert.equal(s.clashes.length,0);s=battleSignals({units:base.map(u=>({...u,moving:false}))});assert.equal(s.marches.length,0);const enemies=base.slice(0,4).map(u=>({...u,id:'enemy-'+u.id,side:'human',x:u.x+60,action:{until:1000}}));s=battleSignals({units:[...base.map(u=>({...u,action:{until:1000}})),...enemies]});assert.equal(s.marches.length,0);assert(s.clashes.length>0);});
test('the camera visits the attacked landmark, returns to its leader, and does not repeatedly replay one continuous siege',()=>{const {w,s}=fixture();attack(w,s);w.time=50;updateCampaign(w,50);const state=w.snapshot(),camera=new Camera('demon');camera.follow(state,.05);for(let i=0;i<55;i++)camera.follow(state,.05);assert.equal(camera.report.id,s.id);assert(Math.hypot(camera.x-s.x,camera.y-(s.y-55))<90);for(let i=0;i<150;i++)camera.follow(state,.05);assert.equal(camera.report,null);assert(Math.abs(camera.x-state.heroes.demon.x)<camera.w*.4);const shots=new SiteCamera('demon');shots.update(state,.1);const elapsed=shots.elapsed;state.paused=true;assert.equal(shots.update(state,20).id,s.id);assert.equal(shots.elapsed,elapsed);state.paused=false;assert.equal(shots.update(state,20,true),null);assert.equal(shots.elapsed,elapsed);state.mode='settlement';assert.equal(shots.update(state,30),null);assert.equal(shots.elapsed,elapsed);});
test('camera viewport rectangles stay inside the tactical map even near the map boundaries',()=>{const {w}=fixture();for(const x of [1500,10240,18900])for(const expansion of [0,1]){const camera=new Camera('demon',855,540);camera.x=x;camera.y=1100;const {box,viewport:v}=tacticalMapLayout(w.snapshot(),camera,expansion);assert(v.x>=box.x&&v.x+v.w<=box.x+box.w+1e-8);assert(v.y>=box.y&&v.y+v.h<=box.y+box.h+1e-8);assert(v.w>40&&v.h>20);}});
test('Luna gets siege state and bounded strategy choices; stale strategy and audience attempts cannot override a fresh defense',()=>{const g=new LiveGame();try{const w=g.world,c=g.context('demon'),decision={strategy:'defend_grain',tactic:'hold',lane:0,speech:'粮仓那边有人！枪手跟我回去。',memory:'粮仓遭袭'};assert(modelRequest('luna-max',c).text.format.schema.properties.strategy.enum.includes('defend_grain'));assert(g.applyDecision(c,decision,'gpt-5.6-luna'));assert.equal(w.campaign.orders.demon.source,'model');assert.equal(campaignGoal(w,w.heroes.demon,{leader:true}).site.kind,'grain');const old=g.context('demon'),site=w.campaign.sites.find(s=>s.owner==='demon');attack(w,site);w.time+=1000;updateCampaign(w,50);assert(!g.applyDecision(old,{...decision,strategy:'raid_forge'},'gpt-5.6-luna'));const fresh=g.context('demon');assert(fresh.campaign.sites.some(s=>s.assault));assert.throws(()=>validateDecision(JSON.stringify({...decision,strategy:'execute_shell'}),fresh));const reply={...fresh,audience:{selected:{id:'q',advice:null}}};assert.deepEqual(modelRequest('luna-max',reply).text.format.schema.properties.strategy.enum,['auto']);assert.throws(()=>validateDecision(JSON.stringify({...decision,replyTo:'q',audienceAction:'none'}),reply));}finally{g.close();}});
test('new alarms are scheduled ahead of routine thinking without removing cadence limits; ceremony freezes siege clocks',()=>{const {w,s}=fixture(),schedule=new DecisionSchedule();schedule.personas=Object.fromEntries(Object.entries(w.heroes).map(([side,h])=>[side,h.id]));schedule.last={demon:100000,human:99000};attack(w,s);w.time=50;updateCampaign(w,50);assert.equal(schedule.take(w,111000),'demon');assert.equal(schedule.take(w,111001),null);const until=s.assault.until;w.mode='settlement';holdBattleClocks(w,5000);assert.equal(s.assault.until,until+5000);});

test('an explicit model defense mobilizes units even before enemies arrive and honors viewer ownership',()=>{const {w,s}=fixture(),viewer=w.units[0];viewer.viewerOrder={kind:'attack',until:50000};commandCampaign(w,'demon','defend_grain',{source:'model'});w.time=1000;updateCampaign(w,50);assert.equal(w.campaign.responses.demon.source,'model');assert.equal(w.campaign.responses.demon.assigned,11);assert(!viewer.defense);assert(w.units.filter(u=>u!==viewer).every(u=>u.defense.siteId===s.id));});

test('a running battlefield moves the commander and nearby defenders toward an attacked site',()=>{const {w,s}=fixture();const enemy=attack(w,s);enemy.speed=0;enemy.hp=enemy.maxHP=1000000;enemy.readyAt=1e12;w.step(50);const guards=w.units.filter(u=>u.defense),before=new Map(guards.map(u=>[u.id,Math.hypot(u.x-s.x,u.y-s.y)])),hero=w.heroes.demon,start=Math.hypot(hero.x-s.x,hero.y-s.y);for(let i=0;i<160;i++)w.step(50);assert(guards.filter(u=>before.get(u.id)-Math.hypot(u.x-s.x,u.y-s.y)>50).length>=2);assert(start-Math.hypot(hero.x-s.x,hero.y-s.y)>100);});
