import test from 'node:test';import assert from 'node:assert/strict';
import {encodeFrame,decodeFrame} from '../modules/pixel-war/public/wire.mjs';
import {LiveGame} from '../modules/live-runtime/game.mjs';
test('unchanged terrain reuses the last revision through real JSON serialization',()=>{const g=new LiveGame();try{const s=g.snapshot();s.terrainChanges=Object.fromEntries(Array.from({length:512},(_,i)=>[i,{at:i,kind:8,blast:{x:i*32,y:1200,r:100}}]));const full=decodeFrame(JSON.parse(JSON.stringify(encodeFrame(s))));const text=JSON.stringify(encodeFrame({...s,time:s.time+100},{reuseTerrain:true})),next=decodeFrame(JSON.parse(text),full);assert.equal(next.terrainChanges,full.terrainChanges);assert(text.length<JSON.stringify(encodeFrame(s)).length*.5);assert.equal(next.time,s.time+100);assert.deepEqual(next.units,full.units);}finally{g.close();}});
test('reset/reconnect never borrows terrain from a different field or revision; full frames recover',()=>{const g=new LiveGame();try{const a=g.snapshot(),delta=encodeFrame(a,{reuseTerrain:true});assert.throws(()=>decodeFrame(delta));assert.throws(()=>decodeFrame(delta,{...a,fieldEpoch:a.fieldEpoch+1}));assert.throws(()=>decodeFrame(delta,{...a,terrainRevision:a.terrainRevision+1}));g.resetForLaunch();const b=decodeFrame(encodeFrame(g.snapshot()),a);assert.notEqual(b.fieldEpoch,a.fieldEpoch);assert.deepEqual(b.terrainChanges,{});}finally{g.close();}});

test('real SSE negotiates terrain reuse and sends a complete reset frame through the owner route',async()=>{
 const {createPreview}=await import('../modules/duel-preview/server.mjs');const app=await createPreview({stagePort:19984,controlPort:19985,clock:false}),abort=new AbortController();
 try{const base='http://127.0.0.1:19985',html=await(await fetch(base)).text(),token=html.match(/name="owner-token" content="([^"]+)"/)[1];const response=await fetch('http://127.0.0.1:19984/stream?terrain=1',{signal:abort.signal}),reader=response.body.getReader();let buffer='';async function frame(){while(!buffer.includes('\n\n')){const v=await reader.read();if(v.done)throw Error('stream_closed');buffer+=new TextDecoder().decode(v.value);}const at=buffer.indexOf('\n\n'),chunk=buffer.slice(0,at);buffer=buffer.slice(at+2);return JSON.parse(chunk.slice(6));}
 const first=await frame();assert(!first.reuseTerrain);let current=decodeFrame(first),delta;for(let i=0;i<5;i++){delta=await frame();current=decodeFrame(delta,current);if(delta.reuseTerrain)break;}assert(delta.reuseTerrain);
 const reset=await fetch(base+'/owner/reset',{method:'POST',headers:{Origin:base,'Content-Type':'application/json','X-Owner-Token':token},body:JSON.stringify({confirmation:'restart_from_first_generation'})});assert.equal(reset.status,200);
 let fresh;for(let i=0;i<5;i++){const next=await frame();if(next.fieldEpoch!==first.fieldEpoch){fresh=next;break;}}assert(fresh&&!fresh.reuseTerrain);assert.deepEqual(decodeFrame(fresh,current).terrainChanges,{});assert.equal((await fetch('http://127.0.0.1:19984/owner/reset',{method:'POST',body:'{}'})).status,405);abort.abort();
 }finally{abort.abort();await app.close();}
});
