import test from 'node:test';import assert from 'node:assert/strict';
import {PixelWorld} from '../modules/pixel-war/world.mjs';import {LiveGame} from '../modules/live-runtime/game.mjs';
import {UNITS,rawDamage} from '../modules/pixel-war/public/catalog.mjs';
import {trainViewerTroop} from '../modules/pixel-war/viewer-training.mjs';
import {refreshProgress} from '../modules/pixel-war/progression.mjs';
import {applyLegacy} from '../modules/pixel-war/legacy.mjs';import {legacyPackage} from '../modules/pixel-war/public/legacy-catalog.mjs';
import {beginSettlement} from '../modules/pixel-war/settlement.mjs';import {battleScene} from '../modules/pixel-war/public/cinematic.mjs';import {ceremonyTitle} from '../modules/pixel-war/public/ceremony.mjs';
const owner={source:'test',receipt:'test:balance',supporter:{id:'viewer',name:'试玩甲',platform:'test'}};
function fighter(w,kind,side='demon'){assert(w.spawn(side,kind,1,true,owner));return w.units.at(-1);}
test('viewer versions of every unit beat system base stats and retain distinct roles',()=>{for(const kind of Object.keys(UNITS)){const w=new PixelWorld();w.units=[];const u=fighter(w,kind);assert.equal(u.maxHP,UNITS[kind].hp*2);assert.equal(u.attack,Math.round(UNITS[kind].attack*1.4));assert.equal(u.armor,UNITS[kind].armor+12);assert.equal(u.speed,UNITS[kind].speed);assert.equal(u.range,UNITS[kind].range);}});
test('both factions scale to the same current era; light player units survive an elder critical hit',()=>{const w=new PixelWorld();w.mode='test_live';w.units=[];w.heroes.demon=w.makeHero('demon',80);w.heroes.human=w.makeHero('human',73);const a=fighter(w,'scout'),b=fighter(w,'scout','human');assert.equal(a.maxHP,b.maxHP);assert.equal(a.attack,b.attack);assert(a.maxHP>=UNITS.scout.hp*6);const before=a.hp;w.resolveHit(w.heroes.human,a,rawDamage(w.heroes.human,a,true),true);assert(a.hp>0&&a.hp<before);});
test('training does not stack on restore or revive; earned levels remain and upgrades preserve wounds',()=>{const g=new LiveGame();try{g.world.units=[];g.world.mode='test_live';g.testGift({side:'demon',reward:'scouts'});g.drain();const u=g.world.units[0];u.level=3;refreshProgress(u);u.hp=u.maxHP*.4;const hp=u.hp,max=u.maxHP,attack=u.attack;assert(!trainViewerTroop(g.world,u));g.restore(g.capture());const restored=g.world.units.find(v=>v.id===u.id);assert.equal(restored.hp,hp);assert.equal(restored.maxHP,max);assert.equal(restored.attack,attack);g.world.resolveHit(g.world.heroes.human,restored,1e8);g.testGift({side:'demon',reward:'revive'});g.drain();const revived=g.world.units.find(v=>v.id===u.id);assert.equal(revived.life,2);assert.equal(revived.level,3);assert.equal(revived.maxHP,max);assert.equal(revived.attack,attack);assert.equal(revived.hp,max);}finally{g.close();}});
test('legacy packages retain player training and never apply it to system retinues',()=>{const w=new PixelWorld();w.units=[];const p=legacyPackage('demon',10),u=fighter(w,p.unit),system=w.fighter('human',p.unit,UNITS[p.unit],u.x,u.y);applyLegacy(w,u,p);applyLegacy(w,system,p);assert(Math.abs(u.maxHP-system.maxHP*2)<=1);assert(u.attack>system.attack);const before=u.maxHP;applyLegacy(w,u,p);assert.equal(u.maxHP,before);assert.equal(system.viewerTraining,null);});
test('no-player deaths skip empty attribution and awards, yet retain crown and ancestor handoff',()=>{for(const killer of ['system','meteor']){const w=new PixelWorld();w.mode='test_live';const h=w.heroes.human;h.hp=1;w.resolveHit(killer==='system'?w.heroes.demon:null,h,100,false,killer);beginSettlement(w,['human']);const r=w.result;assert.equal(r.honors.finisher,null);assert.equal(r.honors.board.length,0);assert.equal(r.timing.fall,r.timing.awards);assert.equal(r.timing.awards,r.timing.celebrate);assert.equal(r.timing.end,11400);assert(!/最后一击|未归属|未记录/.test(ceremonyTitle(w.snapshot(),'demon').detail));w.time=r.startedAt+r.timing.fall;assert.equal(battleScene(w.snapshot()).phase,'execution');}});
test('player contributions keep their award segment when system lands the final blow',()=>{const w=new PixelWorld();w.mode='test_live';w.units=[];const u=fighter(w,'militia'),h=w.heroes.human;h.hp=100;w.resolveHit(u,h,20);w.resolveHit(w.heroes.demon,h,10000);beginSettlement(w,['human']);const r=w.result;assert.equal(r.honors.board.length,1);assert.equal(r.honors.finisher,null);assert.equal(r.timing.awards,r.timing.fall);w.time=r.startedAt+r.timing.awards;assert.equal(battleScene(w.snapshot()).phase,'awards');});
