import {avatarSource,avatarKey} from './public-profile.mjs';
export function imageDimensions(bytes){
 if(bytes.length>=24&&bytes.toString('ascii',12,16)==='IHDR'&&!bytes.includes(Buffer.from('acTL'))&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return{type:'image/png',width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};
 if(bytes[0]===255&&bytes[1]===216){let i=2;while(i+9<bytes.length){if(bytes[i++]!==255)continue;let marker=bytes[i++];while(marker===255)marker=bytes[i++];if(marker===0||marker===216||marker>=208&&marker<=215)continue;if(marker===217||marker===218)break;const len=bytes.readUInt16BE(i);if(len<2||i+len>bytes.length)break;if([192,193,194].includes(marker))return{type:'image/jpeg',width:bytes.readUInt16BE(i+5),height:bytes.readUInt16BE(i+3)};i+=len;}}
 throw Error('unsupported_avatar');
}
export class AvatarStore{
 constructor({db,fetcher=fetch,now=()=>Date.now()}){this.db=db;this.fetcher=fetcher;this.now=now;this.cache=new Map();this.pending=new Map();this.failed=new Map();db.exec('CREATE TABLE IF NOT EXISTS avatar_sources (key TEXT PRIMARY KEY, url TEXT NOT NULL, at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS avatar_inline (key TEXT PRIMARY KEY, type TEXT NOT NULL, base64 TEXT NOT NULL, at INTEGER NOT NULL)');}
 registerInline(value){if(!value)return null;if(typeof value.base64!=='string'||value.base64.length>12000||!/^[A-Za-z0-9+/]+={0,2}$/.test(value.base64))throw Error('avatar_size');const bytes=Buffer.from(value.base64,'base64'),d=imageDimensions(bytes);if(d.type!==value.type||d.width<1||d.height<1||d.width>256||d.height>256)throw Error('avatar_dimensions');const base64=bytes.toString('base64'),key=avatarKey('inline:'+base64);this.db.prepare('INSERT INTO avatar_inline VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET at=excluded.at').run(key,d.type,base64,this.now());this.db.exec('DELETE FROM avatar_inline WHERE key NOT IN (SELECT key FROM avatar_inline ORDER BY at DESC LIMIT 512)');return key;}
 register(url){const safe=avatarSource(url);if(!safe)return null;const key=avatarKey(safe);this.db.prepare('INSERT INTO avatar_sources VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET at=excluded.at').run(key,safe,this.now());this.db.exec('DELETE FROM avatar_sources WHERE key IN (SELECT key FROM avatar_sources ORDER BY at DESC LIMIT -1 OFFSET 512)');return key;}
 async get(key){if(typeof key!=='string'||!/^[a-f0-9]{40}$/.test(key))return null;if(this.cache.has(key))return this.cache.get(key);if(this.failed.get(key)>this.now())return null;if(this.pending.has(key))return this.pending.get(key);if(this.pending.size>=3)return null;
  const inline=this.db.prepare('SELECT type,base64 FROM avatar_inline WHERE key=?').get(key);if(inline)return inline;
  const url=this.db.prepare('SELECT url FROM avatar_sources WHERE key=?').get(key)?.url;if(!url||!avatarSource(url))return null;
  const p=(async()=>{try{const r=await this.fetcher(url,{redirect:'error',signal:AbortSignal.timeout(5000),headers:{Accept:'image/png,image/jpeg'}});if(!r.ok)throw Error('avatar_unavailable');let size=0;const chunks=[];for await(const b of r.body){size+=b.length;if(size>512*1024)throw Error('avatar_size');chunks.push(Buffer.from(b));}const bytes=Buffer.concat(chunks),d=imageDimensions(bytes);if(d.width<1||d.height<1||d.width>1024||d.height>1024)throw Error('avatar_dimensions');const out={type:d.type,base64:bytes.toString('base64')};this.cache.set(key,out);while(this.cache.size>48)this.cache.delete(this.cache.keys().next().value);return out;}catch{this.failed.set(key,this.now()+60000);while(this.failed.size>512)this.failed.delete(this.failed.keys().next().value);return null;}finally{this.pending.delete(key);}})();this.pending.set(key,p);return p;
 }
}
