import {currentRoomGifts} from './room-gifts.mjs';
import {PLATFORM_GIFTS} from './gift-catalog.mjs';
import {runtimeAvailability} from './availability.mjs';
export function launchReadiness(game,status={}){
 const r=runtimeAvailability(status),b=status.bilibili||{},v=status.voice||{},counts=b.eventCounts||{},mapped=Object.keys(game.meta.mappings||{}).length,applied=game.meta.lastDecision||{},evidence=game.liveSessionEvidence(b),verified=b.state==='authenticated'&&game.meta.liveEnabled&&!!evidence.chat&&!!evidence.gift;
 return {localPlayable:true,platformPlayReady:false,streamingVerified:false,
  ai:{connected:status.models?.transport==='api'?r.modelEnabled&&status.models.calls>0:!!status.models?.authenticated,available:r.modelEnabled,reason:r.modelReason,model:status.models?.model||null,activity:game.meta.modelActivity||{sides:{},recent:[]},controllers:Object.fromEntries(['demon','human'].map(side=>{const c=game.meta.lastCommand?.[side],current=c?.persona===game.world.heroes[side].id;return [side,current?{...c,ageMs:Math.max(0,game.world.time-c.at),active:game.world.time-c.at<30000}:null];})),lastApplied:Object.fromEntries(['demon','human'].map(s=>[s,Number.isFinite(applied[s])?{at:applied[s],ageMs:Math.max(0,game.world.time-applied[s]),model:game.meta.models[s]}:null])),commands:['抢粮仓','夺工坊','回防粮仓','守工坊','部署路线','集火','撤退']},
  voice:{activity:game.meta.voiceActivity||{sides:{},played:0,failed:0},enabled:r.voiceEnabled,provider:v.provider||'cloud',fullReadAvailable:r.voiceEnabled,reason:v.local?.memoryReady===false?'local_voice_memory_pressure':!v.enabled?'disabled':null,mode:r.voiceEnabled?'dynamic':'prerecorded_and_subtitles'},
  bilibili:{configured:!!b.configured,connected:b.state==='authenticated',state:b.state||'not_configured',received:b.accepted||0,chatReceived:counts.chat||0,giftReceived:counts.gift||0,mappedGifts:Object.keys(game.meta.mappings||{}).filter(k=>k.startsWith('bilibili:')).length,catalogGifts:currentRoomGifts(status,'bilibili',game.now())?.gifts.length||0,redemptionEnabled:game.meta.liveEnabled,authorizedRoundTripVerified:verified,receiptEvidence:evidence},
  xiaohongshu:{adapterReady:!!status.xiaohongshu?.adapterReady,relayReceiving:status.xiaohongshu?.state==='relay_receiving',receiptEvidence:game.liveSessionEvidence(status.xiaohongshu,'xiaohongshu'),connected:false,catalogGifts:currentRoomGifts(status,'xiaohongshu',game.now())?.gifts.length||0,reason:'official_gift_transport_unverified'},
  broadcast:{demon:'http://127.0.0.1:4390/?side=demon&broadcast=1',human:'http://127.0.0.1:4390/?side=human&broadcast=1',mode:'browser_source_only',pushConfigured:false},
  blockers:['尚未完成真实直播推流和回看验证',...(!game.meta.liveEnabled?['真实礼物兑换尚未启用']:[]),...(!verified?['本次 B站连接尚无弹幕入场和礼物实际兑现凭证']:[]),...(b.state==='authenticated'?[]:['B站需要开发者应用与主播授权']),...(!(mapped+PLATFORM_GIFTS.bilibili.length)?['B站尚未绑定实际礼物']:[]),'小红书缺少已验证的礼物/弹幕传输接口',...(!r.voiceEnabled?['动态朗读未启用']:[]),...(!r.modelEnabled?['魔女解说当前不可用，暂不回应留言']:[])]};
}
