import {randomUUID} from 'node:crypto';
import {boundedJson} from './models.mjs';
export function audioEndpoint(raw){const u=new URL(raw);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!/^dashscope-result-[a-z0-9-]+\.oss-[a-z0-9-]+\.aliyuncs\.com$/.test(u.hostname))throw Error('audio_endpoint_rejected');u.protocol='https:';return u.href;}
export class CharacterVoice {
 constructor({db,config,fetcher=fetch,now=()=>Date.now(),localRequest=null,localCancel=()=>{}}){this.localRequest=localRequest;this.localCancel=localCancel;this.db=db;this.config=config;this.fetcher=fetcher;this.now=now;this.busy=false;this.state='disabled';db.exec('CREATE TABLE IF NOT EXISTS voice_usage(id TEXT PRIMARY KEY,at INTEGER NOT NULL,characters INTEGER NOT NULL)');}
 usage(){const count=since=>this.db.prepare('SELECT COALESCE(SUM(characters),0) AS n FROM voice_usage WHERE at>=?').get(since).n;return {hourCharacters:count(this.now()-3600000),dayCharacters:count(this.now()-86400000)};}
 stop(){this.controller?.abort();this.localCancel();this.state='disabled';}
 async speak({side,text,rank=0}){const cfg=this.config();if(!cfg.enabled||(cfg.provider!=='local'&&!cfg.apiKey))return {ok:false,reason:'voice_key_required'};if(this.busy)return {ok:false,reason:'busy'};if(!['demon','human','empress'].includes(side)||typeof text!=='string'||text.length<1||text.length>260||!Number.isInteger(rank)||rank<0||rank>10000)throw Error('invalid_speech');const usage=this.usage();if(usage.hourCharacters+text.length>cfg.hourCharacters||usage.dayCharacters+text.length>cfg.dayCharacters){this.state='character_budget_limit';return {ok:false,reason:this.state};}
  const usageId=randomUUID();this.db.prepare('INSERT INTO voice_usage VALUES(?,?,?)').run(usageId,this.now(),text.length);this.busy=true;const controller=new AbortController();this.controller=controller;const timer=setTimeout(()=>controller.abort(),cfg.provider==='local'?44000:15000);this.state='synthesizing';
  try{if(cfg.provider==='local'){if(!this.localRequest)throw Error('local_unavailable');const r=await this.localRequest({side,text,rank},controller.signal);if(!r.ok&&['voice_warming','local_voice_memory_pressure','busy'].includes(r.reason)){this.db.prepare('DELETE FROM voice_usage WHERE id=?').run(usageId);this.state=r.reason;return r;}if(!r.ok||typeof r.wav!=='string'||r.wav.length>2800000)throw Error('local_voice_failed');const wav=Buffer.from(r.wav,'base64');if(wav.subarray(0,4).toString()!=='RIFF'||wav.subarray(8,12).toString()!=='WAVE'||controller.signal.aborted||!this.config().enabled)throw Error('invalid_audio');this.state='ready';return {ok:true,wav:r.wav};}const base=cfg.region==='singapore'?'https://dashscope-intl.aliyuncs.com':'https://dashscope.aliyuncs.com';const response=await this.fetcher(base+'/api/v1/services/aigc/multimodal-generation/generation',{method:'POST',redirect:'error',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${cfg.apiKey}`},body:JSON.stringify({model:'qwen3-tts-instruct-flash',input:{text,voice:side==='empress'?(cfg.empressVoice||'Serena'):side==='demon'?cfg.demonVoice:cfg.humanVoice,language_type:'Chinese',instructions:`普通话，${rank>0?'略年迈、威严但会嘴硬':'年轻成年、情绪鲜明'}的${side==='empress'?'女帝':side==='demon'?'魔王':'勇者'}，游戏战场上的短促台词，自然有呼吸，${side==='demon'?'低沉、故作镇定':'明亮、倔强'}，不模仿任何真人。`,optimize_instructions:true}})});const data=await boundedJson(response);const url=audioEndpoint(data.output?.audio?.url);const audio=await this.fetcher(url,{redirect:'error',signal:controller.signal});if(!audio.ok)throw Error('audio_failed');let size=0,parts=[];for await(const part of audio.body){size+=part.length;if(size>2*1024*1024)throw Error('audio_limit');parts.push(Buffer.from(part));}const wav=Buffer.concat(parts);if(wav.subarray(0,4).toString()!=='RIFF'||wav.subarray(8,12).toString()!=='WAVE')throw Error('invalid_wav');if(controller.signal.aborted||!this.config().enabled)throw Error('cancelled');this.state='ready';return {ok:true,wav:wav.toString('base64')};
  }catch{if(cfg.provider==='local')this.db.prepare('DELETE FROM voice_usage WHERE id=?').run(usageId);this.state='recorded_voice_fallback';return {ok:false,reason:this.state};}finally{clearTimeout(timer);this.busy=false;this.controller=null;}
 }
}
